### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by soyatlas** [EvilBT/ComfyUI_SLK_joy_caption_two#106]
# ComfyUI Error Report
## Error Details
- **Node ID:** 173
- **Node Type:** Joy_caption_two_advanced
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 455, in generate
    joy_two_pipeline.parent.loadModels()

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)

  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()

```
## System Information
- **ComfyUI Version:** v0.3.9-26-g19a64d6
- **Arguments:** J:\STABILITYMATRIXDATA\Packages\ComfyUI\main.py --preview-method auto --listen --output-directory Y:\COMFYUI\ --input-directory Y:\COMFYUI\input\ --temp-directory Y:\COMFYUI\temporales\
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769279488
  - **VRAM Free:** 24438112256
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-12-28T08:00:02.319075 - 
[1m[1;34m[LoRA Sidebar]:[0m Building LoRA cache[0m |[96m███████████████████████████████████████████████[94m▒▒▒[0m| [92m 95.4%[0m (2385/2499)2024-12-28T08:00:02.325075 - 
[1m[1;34m[LoRA Sidebar]:[0m Building LoRA cache[0m |[96m███████████████████████████████████████████████[94m▒▒▒[0m| [92m 95.5%[0m (2386/2499)2024-12-28T08:00:02.330075 - 

...

[1m[1;34m[LoRA Sidebar]:[0m Building LoRA cache[0m |[96m█████████████████████████████████████████████████[94m▒[0m| [92m100.0%[0m (2498/2499)2024-12-28T08:00:02.928076 - 
[1m[1;34m[LoRA Sidebar]:[0m Building LoRA cache[0m |[96m██████████████████████████████████████████████████[94m[0m| [92m100.0%[0m (2499/2499)2024-12-28T08:00:02.928076 - 2024-12-28T08:00:02.928076 - 
[1;34m[LoRA Sidebar]:[0m [92mCache build complete![0m2024-12-28T08:00:02.928076 - 
2024-12-28T08:00:03.295076 - [1;34m[LoRA Sidebar]:[0m LoRA cache built in[96m 30.39 seconds[0m2024-12-28T08:00:03.295076 - 
2024-12-28T08:00:03.295076 - [1;34m[LoRA Sidebar]:[0m Total LoRAs processed:[1m 2499[0m2024-12-28T08:00:03.295076 - 
2024-12-28T08:00:03.295076 - [1;34m[LoRA Sidebar]:[0m [1m[93mYour LoRA collection is award winng, just don't ask which one! 🥇[0m
2024-12-28T08:00:03.295076 - 
2024-12-28T08:00:03.311076 - Traceback (most recent call last):
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\nodes.py", line 2089, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'J:\\STABILITYMATRIXDATA\\Packages\\ComfyUI\\custom_nodes\\ComfyUI_NAI-mod\\__init__.py'

2024-12-28T08:00:03.311076 - Cannot import J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_NAI-mod module for custom nodes: [Errno 2] No such file or directory: 'J:\\STABILITYMATRIXDATA\\Packages\\ComfyUI\\custom_nodes\\ComfyUI_NAI-mod\\__init__.py'
2024-12-28T08:00:03.336076 - [92m[tinyterraNodes] [32mLoaded[0m2024-12-28T08:00:03.336076 - 
2024-12-28T08:00:05.173075 - [36;20m[comfy_mtb] | INFO -> loaded [96m88[0m nodes successfuly[0m
2024-12-28T08:00:05.174074 - [36;20m[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://0.0.0.0,:::8188/mtb if you want more information.[0m
2024-12-28T08:00:05.187077 - Initializing ControlAltAI Nodes2024-12-28T08:00:05.187077 - 
2024-12-28T08:00:05.195075 - 
 FlowState Nodes
  - System initializing...2024-12-28T08:00:05.195075 - 
2024-12-28T08:00:05.197075 -   - Loading custom nodes...2024-12-28T08:00:05.197075 - 
2024-12-28T08:00:05.198075 -     - Loaded Unified Video Sampler node.2024-12-28T08:00:05.198075 - 
2024-12-28T08:00:05.201075 -     - Setting UNET_LIST_PATH to: <function <lambda> at 0x0000028F2BCAB400>2024-12-28T08:00:05.201075 - 
2024-12-28T08:00:05.207075 -     - Loaded Unified Sampler.2024-12-28T08:00:05.207075 - 
2024-12-28T08:00:05.208075 -     - Loaded Unified Prompt & Prompt Output nodes.2024-12-28T08:00:05.208075 - 
2024-12-28T08:00:05.406076 -     - HAVE LLAMA CUDA2024-12-28T08:00:05.406076 - 
2024-12-28T08:00:05.407076 -     - Load Unified Model Loader node.2024-12-28T08:00:05.407076 - 
2024-12-28T08:00:05.409075 -     - Loaded Latent Chooser node.2024-12-28T08:00:05.409075 - 
2024-12-28T08:00:05.410076 -     - Loaded Unified Styler node.2024-12-28T08:00:05.410076 - 
2024-12-28T08:00:05.412076 -   - Nodes Loaded.2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -   - Loading node name mappings...2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -   - Mappings Loaded. Available nodes:2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateUnifiedVideoSampler: <class 'FlowState-Nodes.FlowStateUnifiedVideoSampler.FlowStateUnifiedVideoSampler'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateUnifiedSampler: <class 'FlowState-Nodes.FlowStateUnifiedSampler.FlowStateUnifiedSampler'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateUnifiedModelLoader: <class 'FlowState-Nodes.FlowStateUnifiedModelLoader.FlowStateUnifiedModelLoader'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateUnifiedPrompt: <class 'FlowState-Nodes.FlowStateUnifiedPrompt.FlowStateUnifiedPrompt'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStatePromptOutput: <class 'FlowState-Nodes.FlowStateUnifiedPrompt.FlowStatePromptOutput'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateLatentChooser: <class 'FlowState-Nodes.FlowStateLatentChooser.FlowStateLatentChooser'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.413076 -     - FlowStateUnifiedStyler: <class 'FlowState-Nodes.FlowStateUnifiedStyler.FlowStateUnifiedStyler'>2024-12-28T08:00:05.413076 - 
2024-12-28T08:00:05.429075 - Please 'pip install xformers'2024-12-28T08:00:05.429075 - 
2024-12-28T08:00:05.432075 - Nvidia APEX normalization not installed, using PyTorch LayerNorm2024-12-28T08:00:05.432075 - 
2024-12-28T08:00:05.591075 - 
2024-12-28T08:00:05.591075 - [92m[rgthree-comfy] Loaded 42 magnificent nodes. 🎉[00m2024-12-28T08:00:05.591075 - 
2024-12-28T08:00:05.591075 - 
2024-12-28T08:00:05.623076 - [92m[💾 save_image_extended] AVIF   is supported! Woohoo![0m2024-12-28T08:00:05.623076 - 
2024-12-28T08:00:06.136076 - [92m[💾 save_image_extended] JPEGXL is supported! YeePee![0m2024-12-28T08:00:06.136076 - 
2024-12-28T08:00:06.136076 - [92m[💾 save_image_extended][0m version: 2.76[0m2024-12-28T08:00:06.136076 - 
2024-12-28T08:00:07.248073 - [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m2024-12-28T08:00:07.248073 - 
2024-12-28T08:00:07.248073 - [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m2024-12-28T08:00:07.248073 - 
2024-12-28T08:00:08.340074 - [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m218[0m [32mnodes successfully.[0m2024-12-28T08:00:08.340074 - 
2024-12-28T08:00:08.340074 - 
	[3m[93m"Art is not what you see, but what you make others see."[0m[3m - Edgar Degas[0m
2024-12-28T08:00:08.340074 - 
2024-12-28T08:00:08.346075 - [31m[94m[WAS Extras][0m Loading extra custom nodes...2024-12-28T08:00:08.346075 - 
2024-12-28T08:00:08.351074 - [31m[94m[WAS Extras][0m  Import times for extras:2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\ConditioningBlend.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\DebugThis.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\VAEEncodeForInpaint.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\VividSharpen.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.351074 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras\BLVaeEncode.py2024-12-28T08:00:08.351074 - 
2024-12-28T08:00:08.373073 - 
Import times for custom nodes:
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\srl-nodes
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-GPU-temperature-protection
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\Save_Florence2_Bulk_Prompts
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui-image-round
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui_lora_tag_loader
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-12-28T08:00:08.373073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\cg-use-everywhere
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyLiterals
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\civitai_comfy_nodes
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\wlsh_nodes
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ControlFlowUtils
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_cspnodes
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\WAS_Extras
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ControlAltAI-Nodes
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui_face_parsing
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-LTXTricks
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-12-28T08:00:08.374073 -    0.0 seconds (IMPORT FAILED): J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_NAI-mod
2024-12-28T08:00:08.374073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfy-image-saver
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\x-flux-comfyui
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui_bmad_nodes
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\rgthree-comfy
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-12-28T08:00:08.375073 -    0.0 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-LTXVideo
2024-12-28T08:00:08.375073 -    0.1 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-12-28T08:00:08.375073 -    0.1 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-12-28T08:00:08.375073 -    0.1 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui-reactor-node
2024-12-28T08:00:08.375073 -    0.2 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\FlowState-Nodes
2024-12-28T08:00:08.375073 -    0.2 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-12-28T08:00:08.375073 -    0.4 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-12-28T08:00:08.375073 -    0.4 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui-portrait-master
2024-12-28T08:00:08.375073 -    0.5 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\save-image-extended-comfyui
2024-12-28T08:00:08.375073 -    0.6 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Marigold
2024-12-28T08:00:08.375073 -    0.7 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-28T08:00:08.375073 -    1.1 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-JNodes
2024-12-28T08:00:08.376073 -    1.5 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfy_mtb
2024-12-28T08:00:08.376073 -    1.8 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Griptape
2024-12-28T08:00:08.376073 -    2.1 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-12-28T08:00:08.376073 -    2.2 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-12-28T08:00:08.376073 -    2.4 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-12-28T08:00:08.376073 -    3.2 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-12-28T08:00:08.376073 -    5.6 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
2024-12-28T08:00:08.376073 -    6.2 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
2024-12-28T08:00:08.376073 -    9.7 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\comfyui-art-venture
2024-12-28T08:00:08.376073 -   30.4 seconds: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_LoRA_Sidebar
2024-12-28T08:00:08.376073 - 
2024-12-28T08:00:08.400074 - Starting server

2024-12-28T08:00:08.400074 - To see the GUI go to: http://0.0.0.0:8188
2024-12-28T08:00:08.401074 - To see the GUI go to: http://[::]:8188
2024-12-28T08:00:33.348074 - FETCH DATA from: J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-28T08:00:33.348074 - 2024-12-28T08:00:33.457073 -  [DONE]2024-12-28T08:00:33.457073 - 
2024-12-28T08:00:40.119073 - []2024-12-28T08:00:40.119073 - 
2024-12-28T08:00:40.119073 - []2024-12-28T08:00:40.119073 - 
2024-12-28T08:01:25.594076 - got prompt
2024-12-28T08:01:25.761075 - J:\STABILITYMATRIXDATA\Packages\ComfyUI\models\clip\siglip-so400m-patch14-3842024-12-28T08:01:25.761075 - 
2024-12-28T08:01:27.248075 - !!! Exception during processing !!! 
2024-12-28T08:01:27.273075 - Traceback (most recent call last):
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 268, in generate
    self.loadModels()
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
AssertionError

2024-12-28T08:01:27.274075 - Prompt executed in 1.64 seconds
2024-12-28T08:11:56.775074 - got prompt
2024-12-28T08:11:56.849076 - J:\STABILITYMATRIXDATA\Packages\ComfyUI\models\clip\siglip-so400m-patch14-3842024-12-28T08:11:56.849076 - 
2024-12-28T08:11:58.115075 - !!! Exception during processing !!! 
2024-12-28T08:11:58.115075 - Traceback (most recent call last):
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 455, in generate
    joy_two_pipeline.parent.loadModels()
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
  File "J:\STABILITYMATRIXDATA\Packages\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
AssertionError

2024-12-28T08:11:58.116075 - Prompt executed in 1.30 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":176,"last_link_id":322,"nodes":[{"id":173,"type":"Joy_caption_two_advanced","pos":[3020,-460],"size":[315,242],"flags":{},"order":3,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":319},{"name":"image","type":"IMAGE","link":318},{"name":"extra_options","type":"Extra_Options","link":320}],"outputs":[{"name":"STRING","type":"STRING","links":[321],"slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two_advanced","ttNbgOverride":{"color":"#322","bgcolor":"#533","groupcolor":"#A88"}},"widgets_values":["Descriptive","long","","",false,0.9,0.6],"color":"#322","bgcolor":"#533"},{"id":175,"type":"Joy_extra_options","pos":[2020,-340],"size":[980,442],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"Extra_Options","type":"Extra_Options","links":[320]}],"properties":{"Node name for S&R":"Joy_extra_options","ttNbgOverride":{"color":"#322","bgcolor":"#533","groupcolor":"#A88"}},"widgets_values":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"color":"#322","bgcolor":"#533"},{"id":176,"type":"ShowText|pysssss","pos":[3360,-460],"size":[760,560],"flags":{},"order":4,"mode":0,"inputs":[{"name":"text","type":"STRING","link":321,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss","ttNbgOverride":{"color":"#322","bgcolor":"#533","groupcolor":"#A88"}},"widgets_values":[""],"color":"#322","bgcolor":"#533"},{"id":147,"type":"LoadImage","pos":[1740,-440],"size":[240,440],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[318],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage","ttNbgOverride":{"color":"#322","bgcolor":"#533","groupcolor":"#A88"}},"widgets_values":["2024-07-16-modelo lujan perez-0001.jpg","image"],"color":"#322","bgcolor":"#533"},{"id":174,"type":"Joy_caption_two_load","pos":[2300,-460],"size":[460,60],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[319]}],"properties":{"Node name for S&R":"Joy_caption_two_load","ttNbgOverride":{"color":"#322","bgcolor":"#533","groupcolor":"#A88"}},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"],"color":"#322","bgcolor":"#533"}],"links":[[187,83,0,76,0,"MODEL"],[188,10,0,76,4,"VAE"],[189,83,1,78,0,"CLIP"],[190,83,1,6,0,"CLIP"],[245,130,0,95,0,"MODEL"],[246,130,1,95,1,"CLIP"],[247,130,1,6,0,"CLIP"],[248,130,1,142,0,"CLIP"],[249,130,0,124,0,"MODEL"],[250,127,0,124,3,"LATENT"],[251,126,0,124,4,"VAE"],[256,130,1,6,0,"CLIP"],[257,130,0,87,0,"MODEL"],[258,130,0,95,0,"MODEL"],[259,130,1,95,1,"CLIP"],[260,127,0,124,3,"LATENT"],[261,126,0,124,4,"VAE"],[262,130,1,142,0,"CLIP"],[292,130,1,6,0,"CLIP"],[293,130,0,95,0,"MODEL"],[294,130,1,95,1,"CLIP"],[295,130,0,124,0,"MODEL"],[296,127,0,124,3,"LATENT"],[297,126,0,124,4,"VAE"],[298,130,1,142,0,"CLIP"],[302,130,1,6,0,"CLIP"],[303,130,0,124,0,"MODEL"],[304,127,0,124,3,"LATENT"],[305,126,0,124,4,"VAE"],[306,130,1,142,0,"CLIP"],[318,147,0,173,1,"IMAGE"],[319,174,0,173,0,"JoyTwoPipeline"],[320,175,0,173,2,"Extra_Options"],[321,173,0,176,0,"STRING"]],"groups":[],"config":{},"extra":{"ue_links":[]},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
I use Stability Matrix, then the ComfyUI has the "models" (j:\stabilitymatrixdata\Packages\comfyUI\models) directory symbolic link to 
"master" models directory (j:\stabilitymatrixdata\models)

**Comment by soyatlas** [comment]
PROBLEM: 
I write models/Joy-caption-two directory
and must be:
models/Joy_caption_two

_ and not -

Hope help some.
