### ISSUE TITLE
Supplied state dict for layers.0.mlp.down_proj.weight does not contain

### ISSUE THREAD

**Issue by mephiroth** [EvilBT/ComfyUI_SLK_joy_caption_two#14]
运行后提示错误：Joy_caption_two
Supplied state dict for layers.0.mlp.down_proj.weight does not contain `bitsandbytes__*` and possibly other `quantized_stats` components.

2024-10-15 10:46:14,124 - root - INFO - Prompt executed in 0.90 seconds
2024-10-15 10:51:18,200 - root - INFO - got prompt
2024-10-15 10:51:19,308 - root - ERROR - !!! Exception during processing !!! Supplied state dict for layers.0.mlp.down_proj.weight does not contain `bitsandbytes__*` and possibly other `quantized_stats` components.
2024-10-15 10:51:19,311 - root - ERROR - Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 291, in generate
    joy_two_pipeline.parent.loadModels()
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 254, in loadModels
    self.pipeline.loadModels()
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 223, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 42, in __init__
    clip_model = AutoModel.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4014, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4502, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ComfyUI/venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 975, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(model, param, param_name, param_device, state_dict, unexpected_keys)
  File "/root/ComfyUI/venv/lib/python3.12/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 207, in create_quantized_param
    raise ValueError(
ValueError: Supplied state dict for layers.0.mlp.down_proj.weight does not contain `bitsandbytes__*` and possibly other `quantized_stats` components.

**Comment by EvilBT** [comment]
试下更新 transformers 包，这类一般是包版本的问题
