### ISSUE TITLE
This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

### ISSUE THREAD

**Issue by mr-bob-chang** [EvilBT/ComfyUI_SLK_joy_caption_two#19]
运行插件后出现This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`这个报错，我用pip install flash_attn尝试安装这个环境，但是得到了这样一串报错：

C:\Users\Hard_Core>pip install flash_attn
Collecting flash_attn
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Hard_Core\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-8od6z06n\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-8od6z06n\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-8od6z06n\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Hard_Core\AppData\Local\Temp\pip-build-env-8od6z06n\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

请问这个应该怎么解决呢？

**Comment by EvilBT** [comment]
尝试先更新一下依赖项
```
pip install -U -r custom_nodes/ComfyUI_SLK_joy_caption_two/requirements.txt
```
更新一下项目需要的依赖，你这个问题估计是某个依赖项本身有些旧的，我这边的环境都是全新的

**Comment by mr-bob-chang** [comment]
> 尝试先更新一下依赖项
> 
> ```
> pip install -U -r custom_nodes/ComfyUI_SLK_joy_caption_two/requirements.txt
> ```
> 
> 更新一下项目需要的依赖，你这个问题估计是某个依赖项本身有些旧的，我这边的环境都是全新的

更新之后还是会报这个错
