### ISSUE TITLE
help： File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 50, in __init__     assert (BASE_MODEL_PATH / "clip_model.pt").exists()    

### ISSUE THREAD

**Issue by tiandaoyuxi** [EvilBT/ComfyUI_SLK_joy_caption_two#27]
got prompt
D:\Comfy_UI\ComfyUI\models\clip\siglip-so400m-patch14-384
!!! Exception during processing !!!
Traceback (most recent call last):
  File "d:\Comfy_UI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Comfy_UI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Comfy_UI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "d:\Comfy_UI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 259, in generate
    self.loadModels()
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 254, in loadModels
    self.pipeline.loadModels()
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 223, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 50, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 1.79 seconds

**Comment by tiandaoyuxi** [comment]
![image](https://github.com/user-attachments/assets/2031fb88-a7d0-40b2-918d-fdd8c406222d)

**Comment by tiandaoyuxi** [comment]
WARNING: The script huggingface-cli.exe is installed in 'D:\Comfy_UI\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.21.0 requires requests>=2.32.2, but you have requests 2.31.0 which is incompatible.
gradio 4.44.0 requires typer<1.0,>=0.12; sys_platform != "emscripten", but you have typer 0.9.0 which is incompatible.
gradio 4.44.0 requires urllib3~=2.0, but you have urllib3 1.26.20 which is incompatible.
optimum 1.21.4 requires transformers[sentencepiece]<4.44.0,>=4.29.0, but you have transformers 4.45.2 which is incompatible.
sensevoice-onnx 1.1.0 requires setuptools<=65.0, but you have setuptools 72.1.0 which is incompatible.
torchscale 0.3.0 requires fairscale==0.4.0, but you have fairscale 0.4.13 which is incompatible.
Successfully installed huggingface_hub-0.23.4****
