### ISSUE TITLE
报错 AttributeError: 'NoneType' object has no attribute 'clear_gpu'

### ISSUE THREAD

**Issue by chibimiku** [EvilBT/ComfyUI_SLK_joy_caption_two#36]
（1）
跑批量batch报错，大模型文件也在 没看到有读取文件失败的报错，但读取不存在的选项，也没报错就是
!!! Exception during processing !!! 'NoneType' object has no attribute 'clear_gpu'
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 981, in generate
joy_two_pipeline.llm.clear_gpu(low_vram)
AttributeError: 'NoneType' object has no attribute 'clear_gpu'

（2）每个读图之后报错 ，不知道是否跟上一个有关系
Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']

用的workflow 就是example里的batch

**Comment by EvilBT** [comment]
有更详细的复现步骤吗？example里的有可能没同步更新，你可以根据example，手动添加一下

**Comment by chibimiku** [comment]
> 有更详细的复现步骤吗？example里的有可能没同步更新，你可以根据example，手动添加一下

example里只有这几个节点，只修改了处理节点里读取的图片输入目录、输出目录和模型（模型读取的inst... 那个不是nf4的，好像是fp8？ ）
复现步骤就直接点的开启队列，感觉没啥操作，我猜测看上去LLM没有被正常读取，但是读LLM的那个节点没报错，挂在joy_two主要工作节点上了。 我等会打开尝试重新添加一下看看。

**Comment by chibimiku** [comment]
另外这是我的pip list，搜索了一下有人说重装sentencepiece可解决，试了一下没有效果 ：（


Package                           Version
--------------------------------- --------------------
absl-py                           1.4.0
accelerate                        0.34.2
addict                            2.4.0
aggdraw                           1.3.19
aiohttp                           3.9.1
aioresponses                      0.7.6
aiosignal                         1.3.1
albumentations                    1.3.1
altair                            5.4.1
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             3.6.2
APScheduler                       3.10.1
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
asttokens                         2.2.1
async-timeout                     4.0.3
attrs                             24.2.0
awscli                            1.33.44
Babel                             2.11.0
backcall                          0.2.0
backoff                           2.2.1
beautifulsoup4                    4.11.1
binaryornot                       0.4.4
bitsandbytes                      0.44.1
bleach                            6.0.0
blend_modes                       2.1.0
blind-watermark                   0.4.4
boto3                             1.34.86
botocore                          1.34.162
Brotli                            1.0.9
cachetools                        5.3.0
came-pytorch                      0.1.3
certifi                           2024.8.30
cffi                              1.16.0
chardet                           5.2.0
charset-normalizer                3.3.2
click                             8.1.7
cmake                             3.30.3
codewithgpu                       0.2.8
color-matcher                     0.5.0
colorama                          0.4.4
coloredlogs                       15.0.1
colorlog                          6.8.0
colour-science                    0.4.4
comm                              0.2.2
conda                             22.11.1
conda-content-trust               0.2.0
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
contourpy                         1.0.7
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect2                        0.7.0
cstr                              0.1.0
cycler                            0.11.0
Cython                            3.0.0
dataclasses-json                  0.6.7
ddt                               1.7.2
debugpy                           1.6.6
decorator                         5.1.1
deepdiff                          7.0.1
defusedxml                        0.7.1
diffusers                         0.28.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
docker                            6.1.3
docker-pycreds                    0.4.0
docopt                            0.6.2
docutils                          0.16
easydict                          1.11
einops                            0.7.0
embreex                           2.17.7.post4
exceptiongroup                    1.2.2
executing                         1.2.0
fairscale                         0.4.0
fastapi                           0.110.3
fastjsonschema                    2.16.2
ffmpeg                            1.4
ffmpy                             0.3.0
filelock                          3.13.1
flatbuffers                       23.5.26
flet                              0.24.1
flet-core                         0.24.1
flet-runtime                      0.24.1
fonttools                         4.38.0
fqdn                              1.5.1
frozenlist                        1.4.0
fsspec                            2023.10.0
ftfy                              6.1.3
fvcore                            0.1.5.post20221221
gdown                             5.2.0
gitdb                             4.0.11
GitPython                         3.1.40
google-ai-generativelanguage      0.6.10
google-api-core                   2.20.0
google-api-python-client          2.147.0
google-auth                       2.35.0
google-auth-httplib2              0.2.0
google-auth-oauthlib              0.4.6
google-cloud-core                 2.4.1
google-cloud-storage              2.18.2
google-crc32c                     1.6.0
google-generativeai               0.8.2
google-resumable-media            2.7.2
googleapis-common-protos          1.65.0
GPUtil                            1.4.0
grpcio                            1.51.1
grpcio-status                     1.48.2
h11                               0.14.0
httpcore                          1.0.2
httplib2                          0.22.0
httptools                         0.6.1
httpx                             0.26.0
huggingface-hub                   0.23.4
humanfriendly                     10.0
hydra-core                        1.3.2
idna                              3.7
imageio                           2.33.0
imageio-ffmpeg                    0.4.9
imagesize                         1.4.1
img2texture                       1.0.6
importlib-metadata                6.8.0
inference-cli                     0.17.0
inference-gpu                     0.15.2
iniconfig                         2.0.0
insightface                       0.7.3
iopath                            0.1.10
ipykernel                         6.20.2
ipython                           8.9.0
ipython-genutils                  0.2.0
ipywidgets                        8.1.2
isoduration                       20.11.0
jedi                              0.18.2
Jinja2                            3.1.2
jiter                             0.5.0
jmespath                          1.0.1
joblib                            1.3.2
json5                             0.9.11
jsonpointer                       2.3
jsonschema                        4.17.3
jupyter_client                    8.0.1
jupyter_core                      5.1.5
jupyter-events                    0.6.3
jupyter_server                    2.1.0
jupyter_server_terminals          0.4.4
jupyterlab                        3.5.3
jupyterlab-language-pack-zh-CN    3.5.post4
jupyterlab-pygments               0.2.2
jupyterlab_server                 2.19.0
jupyterlab_widgets                3.0.10
kiwisolver                        1.4.4
kornia                            0.7.2
kornia_rs                         0.1.3
lazy_loader                       0.3
lion-pytorch                      0.2.2
llama_cpp_python                  0.2.89
llvmlite                          0.43.0
loguru                            0.7.2
lxml                              4.9.3
mapbox-earcut                     1.0.1
Markdown                          3.4.1
markdown-it-py                    3.0.0
MarkupSafe                        2.1.2
marshmallow                       3.22.0
matplotlib                        3.6.3
matplotlib-inline                 0.1.6
matrix-client                     0.4.0
mdurl                             0.1.2
mediapipe                         0.10.8
mistune                           2.0.4
mpmath                            1.3.0
mss                               9.0.2
multidict                         6.0.4
mypy-extensions                   1.0.0
narwhals                          1.8.1
nbclassic                         0.5.1
nbclient                          0.7.2
nbconvert                         7.2.9
nbformat                          5.7.3
nest-asyncio                      1.5.6
networkx                          3.2.1
notebook                          6.5.2
notebook_shim                     0.2.2
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.3.101
nvidia-nvtx-cu12                  12.1.105
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.15.0
onnxruntime                       1.19.2
onnxruntime-gpu                   1.15.1
openai                            1.50.0
opencv-contrib-python             4.10.0.84
opencv-contrib-python-headless    4.10.0.84
opencv-python                     4.8.0.76
opencv-python-headless            4.10.0.84
ordered-set                       4.1.0
packaging                         23.2
pandas                            2.1.3
pandocfilters                     1.5.0
parso                             0.8.3
peft                              0.13.2
pendulum                          3.0.0
pexpect                           4.8.0
pickleshare                       0.7.5
piexif                            1.1.3
pilgram                           1.2.1
pillow                            11.0.0
pip                               24.2
platformdirs                      4.0.0
pluggy                            1.5.0
pooch                             1.8.2
portalocker                       2.8.2
prettytable                       3.9.0
prodigyopt                        1.0
prometheus-client                 0.16.0
prometheus-fastapi-instrumentator 6.0.0
prompt-toolkit                    3.0.36
proto-plus                        1.24.0
protobuf                          3.20.3
psd-tools                         1.10.0
psutil                            5.9.4
ptyprocess                        0.7.0
PuLP                              2.9.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pybase64                          1.4.0
pycollada                         0.8
pycosat                           0.6.6
pycparser                         2.21
pydantic                          2.9.2
pydantic_core                     2.23.4
pydantic-settings                 2.5.2
pydot                             3.0.2
Pygments                          2.14.0
PyMatting                         1.1.12
pynvml                            11.5.0
pyOpenSSL                         24.2.1
pyparsing                         3.0.9
pypng                             0.20220715.0
pyrsistent                        0.19.3
PySocks                           1.7.1
pytest                            8.3.3
pytest-asyncio                    0.21.1
python-dateutil                   2.8.2
python-dotenv                     1.0.1
python-json-logger                2.0.4
python-slugify                    8.0.4
pytz                              2022.7.1
PyWavelets                        1.7.0
PyYAML                            6.0
pyzbar                            0.1.9
pyzmq                             25.0.0
qrcode                            7.4.2
qudida                            0.0.4
redis                             5.0.8
regex                             2023.10.3
rembg                             2.0.59
repath                            0.9.0
reportlab                         4.0.7
requests                          2.31.0
requests-file                     2.1.0
requests-oauthlib                 1.3.1
requests-toolbelt                 1.0.0
rf-clip                           1.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.5.2
rsa                               4.7.2
Rtree                             1.3.0
ruamel.yaml                       0.17.21
ruamel.yaml.clib                  0.2.6
s3transfer                        0.10.2
safetensors                       0.4.5
scikit-image                      0.22.0
scikit-learn                      1.3.2
scipy                             1.11.4
seaborn                           0.13.0
segment-anything                  1.0
Send2Trash                        1.8.0
sentencepiece                     0.2.0
sentry-sdk                        2.14.0
setproctitle                      1.3.3
setuptools                        69.5.1
shapely                           2.0.2
six                               1.16.0
skypilot                          0.5.0
smmap                             5.0.1
sniffio                           1.3.0
sounddevice                       0.4.6
soundfile                         0.12.1
soupsieve                         2.3.2.post1
spandrel                          0.3.4
stack-data                        0.6.2
starlette                         0.37.2
structlog                         24.4.0
supervision                       0.22.0
surrealist                        1.0.2
svg.path                          6.3
svglib                            1.5.1
sympy                             1.12
tabulate                          0.9.0
tensorboard                       2.11.2
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
termcolor                         2.3.0
terminado                         0.17.1
text-unidecode                    1.3
thop                              0.1.1.post2209072238
threadpoolctl                     3.2.0
tifffile                          2023.9.26
time-machine                      2.15.0
timm                              0.6.13
tinycss2                          1.2.1
tldextract                        5.1.2
tokenizers                        0.20.1
toml                              0.10.2
tomli                             2.0.1
toolz                             0.12.0
torch                             2.3.1+cu121
torchaudio                        2.3.1+cu121
torchscale                        0.3.0
torchsde                          0.2.6
torchvision                       0.18.1+cu121
tornado                           6.2
tqdm                              4.66.5
traitlets                         5.8.1
trampoline                        0.1.2
transformers                      4.45.2
transparent-background            1.3.2
trimesh                           4.0.10
triton                            2.3.1
typer                             0.9.0
typer-config                      1.4.0
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tzdata                            2023.3
tzlocal                           5.2
ultralytics                       8.2.101
ultralytics-thop                  2.0.8
uri-template                      1.2.0
uritemplate                       4.1.1
urllib3                           1.26.20
uvicorn                           0.30.6
uvloop                            0.20.0
vhacdx                            0.0.5
voluptuous                        0.15.2
wandb                             0.18.1
watchdog                          4.0.2
watchfiles                        0.24.0
wcwidth                           0.2.12
webcolors                         1.12
webencodings                      0.5.1
websocket-client                  1.5.0
websockets                        13.1
Werkzeug                          2.2.2
wget                              3.2
wheel                             0.44.0
widgetsnbextension                4.0.10
xformers                          0.0.27
xxhash                            3.4.1
yacs                              0.1.8
yapf                              0.40.2
yarl                              1.9.3
zipp                              3.17.0
zstandard                         0.22.0
zxing-cpp                         2.2.0

**Comment by chibimiku** [comment]
![image](https://github.com/user-attachments/assets/1bd9387c-f615-4d68-9f21-b0492f58d1a7)

sad story，重新添加了一下，问题还是这样

**Comment by EvilBT** [comment]
你用其他节点会报错吗，先尝试另外几个节点，不是高级批量这个，然后把报错信息贴上来

**Comment by chibimiku** [comment]
# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two
- **Exception Type:** ValueError
- **Exception Message:** Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']
## Stack Trace
```
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 360, in generate
    joy_two_pipeline.loadLLM(joy_two_pipeline.model)

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 235, in loadLLM
    self.llm = JoyLLM(self.load_device, self.offload_device, model_id)

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 157, in __init__
    tokenizer = AutoTokenizer.from_pretrained(os.path.join(BASE_MODEL_PATH, "text_model"), use_fast=True)

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 907, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2208, in from_pretrained
    return cls._from_pretrained(

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2442, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 138, in __init__
    fast_tokenizer = convert_slow_tokenizer(self, from_tiktoken=True)

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1594, in convert_slow_tokenizer
    raise ValueError(

```
## System Information
- **ComfyUI Version:** v0.2.2-78-gd72e871
- **Arguments:** main.py --port=6006
- **OS:** posix
- **Python Version:** 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

試了一下單條數據標註，似乎錯誤是一樣的 看pip版本是這個
transformers                      4.45.2

**Comment by xiangcp** [comment]
检查下你的输入文件夹是否正确，很有可能是你文件夹为空了，这里建议作者在joy_caption_two_node.py 中增加一个输入文件夹异常检测
