### ISSUE TITLE
Weights only load failed.

### ISSUE THREAD

**Issue by lcmaizld** [EvilBT/ComfyUI_SLK_joy_caption_two#47]
加载siglip-so400m-patch14-384 时出错。

```

> /root/autodl-tmp/ComfyUI/models/clip/siglip-so400m-patch14-384
> Loading VLM's custom vision model
> !!! Exception during processing !!! Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60
> Traceback (most recent call last):
>   File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>   File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 268, in generate
>     self.loadModels()
>   File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 263, in loadModels
>     self.pipeline.loadModels()
>   File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 231, in loadModels
>     self.image_adapter = JoyImageAdapter(self.load_device, self.offload_device)
>   File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 133, in __init__
>     image_adapter.load_state_dict(torch.load(adapter_path, map_location=self.offload_device, weights_only=True))
>   File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
>     return _torch_load(*args, **kwargs)
>   File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1039, in load
>     raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
> _pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60

```

**Comment by EvilBT** [comment]
先确定好每个相关模型的是不是已经下载完并放置到正确的位置了（参考截图，有具体的位置说明）然后更新依赖包到最不低于我项目最小依赖版本，如果还有问题，再把详细的环境发上来

**Comment by lcmaizld** [comment]
全都重新下载了，还是出错。
环境如下：
`/root/autodl-tmp/ComfyUI
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-28 17:30:50.078107
** Platform: Linux
** Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
** Python executable: /root/miniconda3/bin/python
** ComfyUI Path: /root/autodl-tmp/ComfyUI
** Log path: /root/autodl-tmp/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.9 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24210 MB, total RAM 1031695 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /root/autodl-tmp/ComfyUI/web
Total VRAM 24210 MB, total RAM 1031695 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V7.7.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)`


错误信息如下：
`
# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two_load
- **Exception Type:** _pickle.UnpicklingError
- **Exception Message:** Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60
## Stack Trace
```
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 268, in generate
    self.loadModels()

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 231, in loadModels
    self.image_adapter = JoyImageAdapter(self.load_device, self.offload_device)

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 133, in __init__
    image_adapter.load_state_dict(torch.load(adapter_path, map_location=self.offload_device, weights_only=True))

  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1039, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None

```
## System Information
- **ComfyUI Version:** v0.2.2-78-gd72e871
- **Arguments:** main.py --port=6006 --disable-metadata --fast
- **OS:** posix
- **Python Version:** 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25386352640
  - **VRAM Free:** 24976752640
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
`

**Comment by lcmaizld** [comment]
已经解决，我的image_adapter 没有下载完整导致。
