### ISSUE TITLE
Expected a cuda device, but got: cpu

### ISSUE THREAD

**Issue by lesteryebin** [EvilBT/ComfyUI_SLK_joy_caption_two#55]
# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two
- **Exception Type:** ValueError
- **Exception Message:** Expected a cuda device, but got: cpu
## Stack Trace
```
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 407, in generate
    generate_ids = text_model.generate(input_ids, inputs_embeds=input_embeds, attention_mask=attention_mask,

  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2024, in generate
    result = self._sample(

  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1189, in forward
    outputs = self.model(

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1001, in forward
    layer_outputs = decoder_layer(

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 617, in forward
    query_states = self.q_proj(hidden_states)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\peft\tuners\lora\bnb.py", line 467, in forward
    result = self.base_layer(x, *args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\nn\modules.py", line 484, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)

  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)

  File "D:\ComfyUI\python\lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]

  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 509, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)

  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 1379, in dequantize_4bit
    device = pre_call(A.device)

  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 482, in pre_call
    torch.cuda.set_device(device)

  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\__init__.py", line 418, in set_device
    device = _get_device_index(device)

  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    raise ValueError(f"Expected a cuda device, but got: {device}")

```
## System Information
- **ComfyUI Version:** v0.2.6-7-gfabf449f
- **Arguments:** D:\ComfyUI\main.py --auto-launch --force-fp32 --fp32-text-enc --preview-method auto --disable-smart-memory --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 15821963264
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-02 17:23:11,725 - root - INFO - Total VRAM 16376 MB, total RAM 32608 MB
2024-11-02 17:23:11,725 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-02 17:23:12,907 - root - INFO - xformers version: 0.0.28.post1
2024-11-02 17:23:12,907 - root - INFO - Forcing FP32, if this improves things please report it.
2024-11-02 17:23:12,907 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 17:23:12,907 - root - INFO - Disabling smart memory management
2024-11-02 17:23:12,907 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-11-02 17:23:13,137 - root - INFO - Using xformers cross attention
2024-11-02 17:23:14,405 - root - INFO - [Prompt Server] web root: D:\ComfyUI\web
2024-11-02 17:23:15,910 - root - INFO - Total VRAM 16376 MB, total RAM 32608 MB
2024-11-02 17:23:15,910 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-02 17:23:15,910 - root - INFO - xformers version: 0.0.28.post1
2024-11-02 17:23:15,910 - root - INFO - Forcing FP32, if this improves things please report it.
2024-11-02 17:23:15,910 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 17:23:15,910 - root - INFO - Disabling smart memory management
2024-11-02 17:23:15,911 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-11-02 17:23:18,875 - root - INFO - --------------
2024-11-02 17:23:18,875 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-02 17:23:18,885 - root - INFO - ChatGPT.available True
2024-11-02 17:23:18,886 - root - INFO - edit_mask.available True
2024-11-02 17:23:19,579 - root - INFO - ClipInterrogator.available True
2024-11-02 17:23:19,821 - root - INFO - PromptGenerate.available True
2024-11-02 17:23:19,821 - root - INFO - ChinesePrompt.available True
2024-11-02 17:23:19,821 - root - INFO - RembgNode_.available True
2024-11-02 17:23:20,214 - root - INFO - TripoSR.available
2024-11-02 17:23:20,214 - root - INFO - MiniCPMNode.available
2024-11-02 17:23:20,216 - root - INFO - Scenedetect.available False
2024-11-02 17:23:20,308 - root - INFO - FishSpeech.available
2024-11-02 17:23:20,311 - root - INFO - SenseVoice.available False
2024-11-02 17:23:20,559 - root - INFO - Whisper.available False
2024-11-02 17:23:20,569 - root - INFO - FalVideo.available
2024-11-02 17:23:20,570 - root - INFO - [93m -------------- [0m
2024-11-02 17:23:30,268 - root - INFO - 
Import times for custom nodes:
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\comfuinoda-Navyblue
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-11-02 17:23:30,268 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-02 17:23:30,269 - root - INFO -    0.0 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-02 17:23:30,269 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-02 17:23:30,269 - root - INFO -    0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-02 17:23:30,270 - root - INFO -    0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-02 17:23:30,270 - root - INFO -    0.7 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-02 17:23:30,270 - root - INFO -    1.5 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-02 17:23:30,270 - root - INFO -    2.7 seconds: D:\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-11-02 17:23:30,270 - root - INFO -    3.6 seconds: D:\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-02 17:23:30,270 - root - INFO -    5.8 seconds: D:\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-02 17:23:30,270 - root - INFO - 
2024-11-02 17:23:30,465 - root - INFO - Starting server

2024-11-02 17:23:30,466 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-02 17:23:46,690 - root - INFO - got prompt
2024-11-02 17:23:49,961 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-02 17:23:49,962 - root - INFO - Loading 1 new model
2024-11-02 17:23:49,973 - root - INFO - loaded completely 0.0 1618.345947265625 True
2024-11-02 17:23:51,687 - root - INFO - Requested to load ImageAdapter
2024-11-02 17:23:51,687 - root - INFO - Loading 1 new model
2024-11-02 17:23:51,688 - root - INFO - loaded completely 0.0 82.078125 True
2024-11-02 17:23:58,129 - root - INFO - Prompt executed in 11.44 seconds
2024-11-02 17:24:25,602 - root - INFO - got prompt
2024-11-02 17:24:31,902 - root - ERROR - !!! Exception during processing !!! Expected a cuda device, but got: cpu
2024-11-02 17:24:31,909 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 407, in generate
    generate_ids = text_model.generate(input_ids, inputs_embeds=input_embeds, attention_mask=attention_mask,
  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2024, in generate
    result = self._sample(
  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1189, in forward
    outputs = self.model(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1001, in forward
    layer_outputs = decoder_layer(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 617, in forward
    query_states = self.q_proj(hidden_states)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\peft\tuners\lora\bnb.py", line 467, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\nn\modules.py", line 484, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "D:\ComfyUI\python\lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 509, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 1379, in dequantize_4bit
    device = pre_call(A.device)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 482, in pre_call
    torch.cuda.set_device(device)
  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\__init__.py", line 418, in set_device
    device = _get_device_index(device)
  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    raise ValueError(f"Expected a cuda device, but got: {device}")
ValueError: Expected a cuda device, but got: cpu

2024-11-02 17:24:31,911 - root - INFO - Prompt executed in 6.30 seconds
2024-11-02 17:25:40,669 - root - INFO - got prompt
2024-11-02 17:25:46,560 - root - ERROR - !!! Exception during processing !!! Expected a cuda device, but got: cpu
2024-11-02 17:25:46,562 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 407, in generate
    generate_ids = text_model.generate(input_ids, inputs_embeds=input_embeds, attention_mask=attention_mask,
  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2024, in generate
    result = self._sample(
  File "D:\ComfyUI\python\lib\site-packages\transformers\generation\utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1189, in forward
    outputs = self.model(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 1001, in forward
    layer_outputs = decoder_layer(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\transformers\models\llama\modeling_llama.py", line 617, in forward
    query_states = self.q_proj(hidden_states)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\peft\tuners\lora\bnb.py", line 467, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\accelerate\hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\nn\modules.py", line 484, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "D:\ComfyUI\python\lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 509, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, quant_state).to(A.dtype).t(), bias)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 1379, in dequantize_4bit
    device = pre_call(A.device)
  File "D:\ComfyUI\python\lib\site-packages\bitsandbytes\functional.py", line 482, in pre_call
    torch.cuda.set_device(device)
  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\__init__.py", line 418, in set_device
    device = _get_device_index(device)
  File "D:\ComfyUI\python\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    raise ValueError(f"Expected a cuda device, but got: {device}")
ValueError: Expected a cuda device, but got: cpu

2024-11-02 17:25:46,565 - root - INFO - Prompt executed in 5.89 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":18,"nodes":[{"id":8,"type":"ShowText|pysssss","pos":{"0":883,"1":222},"size":{"0":315,"1":76},"flags":{},"order":7,"mode":0,"inputs":[{"name":"text","type":"STRING","link":12,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":["","result: finished count: 0, error count: 2"]},{"id":11,"type":"Simple String","pos":{"0":-279,"1":84},"size":{"0":596.0454711914062,"1":62.295921325683594},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"STRING","type":"STRING","links":[13],"shape":3,"label":"字符串"}],"properties":{"Node name for S&R":"Simple String"},"widgets_values":["xb,"]},{"id":10,"type":"Batch_joy_caption_two_advanced","pos":{"0":405,"1":228},"size":{"0":378,"1":390},"flags":{},"order":5,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":11,"label":"joy_two_pipeline"},{"name":"extra_options","type":"Extra_Options","link":10,"label":"extra_options"},{"name":"prefix_caption","type":"STRING","link":13,"widget":{"name":"prefix_caption"},"label":"prefix_caption"}],"outputs":[{"name":"STRING","type":"STRING","links":[12],"slot_index":0,"label":"STRING"}],"properties":{"Node name for S&R":"Batch_joy_caption_two_advanced"},"widgets_values":["D:\\lora-scripts\\test","D:\\lora-scripts\\test",false,"",1,"Descriptive","100","","",false,0.8,0.6,"",""]},{"id":9,"type":"Joy_extra_options","pos":{"0":-297,"1":210},"size":{"0":653.4759521484375,"1":442},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"Extra_Options","type":"Extra_Options","links":[10],"label":"Extra_Options"}],"properties":{"Node name for S&R":"Joy_extra_options"},"widgets_values":[false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false]},{"id":2,"type":"Joy_caption_two_load","pos":{"0":399,"1":97},"size":{"0":378.8418273925781,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[11],"label":"JoyTwoPipeline","slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]},{"id":13,"type":"Joy_caption_two_load","pos":{"0":984,"1":1},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[16],"label":"JoyTwoPipeline","slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]},{"id":14,"type":"ShowText|pysssss","pos":{"0":1711.126708984375,"1":140.88436889648438},"size":[315,58],"flags":{},"order":8,"mode":0,"inputs":[{"name":"text","type":"STRING","link":17,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":12,"type":"Joy_caption_two","pos":{"0":1317.8316650390625,"1":97.63824462890625},"size":{"0":315,"1":126},"flags":{},"order":6,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":16,"label":"joy_two_pipeline"},{"name":"image","type":"IMAGE","link":18,"label":"image"}],"outputs":[{"name":"STRING","type":"STRING","links":[17],"label":"STRING","slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","long",false]},{"id":15,"type":"LoadImage","pos":{"0":1199.5167236328125,"1":378.330078125},"size":[315,314],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[18],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["217941588-496ad657ad81bf2313b8d44c8a6049099d0d5c7494f6b48468e78e8a4d9ca4fe.png","image"]}],"links":[[10,9,0,10,1,"Extra_Options"],[11,2,0,10,0,"JoyTwoPipeline"],[12,10,0,8,0,"STRING"],[13,11,0,10,2,"STRING"],[16,13,0,12,0,"JoyTwoPipeline"],[17,12,0,14,0,"STRING"],[18,15,0,12,1,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7247295000000007,"offset":[448.52363507546875,224.357818144823]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by xuyufeng1995** [comment]
self.load_device = comfy.model_management.get_torch_device()
self.offload_device = comfy.model_management.unet_offload_device()
改一下代码就好了
