### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'embedded_image'

### ISSUE THREAD

**Issue by VangengLab** [EvilBT/ComfyUI_SLK_joy_caption_two#60]
完整的trace：
!!! Exception during processing !!! 'NoneType' object has no attribute 'embedded_image'
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 342, in generate
embedded_images = joy_two_pipeline.image_adapter.embedded_image(vision_outputs.hidden_states)
AttributeError: 'NoneType' object has no attribute 'embedded_image'

**Comment by sljjyy** [comment]
我也遇到了 T..T

**Comment by HimashaHerath** [comment]
any solution ?
