### ISSUE TITLE
求助 Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

### ISSUE THREAD

**Issue by xiuyidesign** [EvilBT/ComfyUI_SLK_joy_caption_two#61]
运行报错，无法使用joycaption two。
完整报告如下

# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two
- **Exception Type:** ImportError
- **Exception Message:** Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`
## Stack Trace
```
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(

  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\python\lib\site-packages\transformers\modeling_utils.py", line 3577, in from_pretrained
    raise ImportError(

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA RTX A5000 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17179344896
  - **VRAM Free:** 15010554040
  - **Torch VRAM Total:** 1006632960
  - **Torch VRAM Free:** 73588920

## Logs
```
2024-11-10 00:40:53,091 - root - INFO - Total VRAM 16384 MB, total RAM 65200 MB
2024-11-10 00:40:53,091 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-10 00:40:54,782 - root - INFO - xformers version: 0.0.27
2024-11-10 00:40:54,783 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-10 00:40:54,783 - root - INFO - Device: cuda:0 NVIDIA RTX A5000 Laptop GPU : cudaMallocAsync
2024-11-10 00:40:55,377 - root - INFO - Using xformers cross attention
2024-11-10 00:40:57,087 - root - INFO - [Prompt Server] web root: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\web
2024-11-10 00:40:57,090 - root - INFO - Adding extra search path checkpoints D:\00 SOFTWARE\sd-webui-aki-v4.9\models/Stable-diffusion
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path configs D:\00 SOFTWARE\sd-webui-aki-v4.9\models/Stable-diffusion
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path vae D:\00 SOFTWARE\sd-webui-aki-v4.9\models/VAE
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path loras D:\00 SOFTWARE\sd-webui-aki-v4.9\models/Lora
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path loras D:\00 SOFTWARE\sd-webui-aki-v4.9\models/LyCORIS
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path upscale_models D:\00 SOFTWARE\sd-webui-aki-v4.9\models/ESRGAN
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path upscale_models D:\00 SOFTWARE\sd-webui-aki-v4.9\models/RealESRGAN
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path upscale_models D:\00 SOFTWARE\sd-webui-aki-v4.9\models/SwinIR
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path embeddings D:\00 SOFTWARE\sd-webui-aki-v4.9\embeddings
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path hypernetworks D:\00 SOFTWARE\sd-webui-aki-v4.9\models/hypernetworks
2024-11-10 00:40:57,091 - root - INFO - Adding extra search path controlnet D:\00 SOFTWARE\sd-webui-aki-v4.9\models/ControlNet
2024-11-10 00:40:59,574 - root - INFO - Total VRAM 16384 MB, total RAM 65200 MB
2024-11-10 00:40:59,574 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-10 00:40:59,574 - root - INFO - xformers version: 0.0.27
2024-11-10 00:40:59,575 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-10 00:40:59,575 - root - INFO - Device: cuda:0 NVIDIA RTX A5000 Laptop GPU : cudaMallocAsync
2024-11-10 00:41:06,480 - root - INFO - 
Import times for custom nodes:
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\websocket_image_save.py
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\FreeU_Advanced
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_TiledKSampler
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\stability-ComfyUI-nodes
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_experiments
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\PowerNoiseSuite
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-10 00:41:06,480 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\images-grid-comfy-plugin
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Custom-Scripts
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\x-flux-comfyui
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\efficiency-nodes-comfyui
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\comfyui-workspace-manager
2024-11-10 00:41:06,481 - root - INFO -    0.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-10 00:41:06,481 - root - INFO -    0.1 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\comfyui_controlnet_aux
2024-11-10 00:41:06,481 - root - INFO -    0.1 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspire-Pack
2024-11-10 00:41:06,481 - root - INFO -    0.1 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Crystools
2024-11-10 00:41:06,481 - root - INFO -    0.1 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-10 00:41:06,481 - root - INFO -    0.3 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_FizzNodes
2024-11-10 00:41:06,481 - root - INFO -    0.4 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
2024-11-10 00:41:06,481 - root - INFO -    0.4 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-KJNodes
2024-11-10 00:41:06,481 - root - INFO -    0.4 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager
2024-11-10 00:41:06,481 - root - INFO -    1.4 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack
2024-11-10 00:41:06,481 - root - INFO -    5.0 seconds: D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-10 00:41:06,481 - root - INFO - 
2024-11-10 00:41:06,501 - root - INFO - Starting server

2024-11-10 00:41:06,502 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-10 00:41:14,863 - root - INFO - got prompt
2024-11-10 00:41:17,001 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-10 00:41:17,001 - root - INFO - Loading 1 new model
2024-11-10 00:41:17,269 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-10 00:41:17,762 - root - INFO - Requested to load ImageAdapter
2024-11-10 00:41:17,762 - root - INFO - Loading 1 new model
2024-11-10 00:41:17,769 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-10 00:41:18,190 - root - ERROR - !!! Exception during processing !!! Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`
2024-11-10 00:41:18,192 - root - ERROR - Traceback (most recent call last):
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "D:\00 SOFTWARE\SD-ComfyUI-aki-v1.4\python\lib\site-packages\transformers\modeling_utils.py", line 3577, in from_pretrained
    raise ImportError(
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`

2024-11-10 00:41:18,194 - root - INFO - Prompt executed in 3.32 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":7,"last_link_id":5,"nodes":[{"id":2,"type":"Joy_caption_two_load","pos":{"0":628,"1":187},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[1],"label":"JoyCaptionTwo"}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct"]},{"id":3,"type":"LoadImage","pos":{"0":608,"1":363},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["11.16小米SU7 (5).png","image"]},{"id":4,"type":"ShowText|pysssss","pos":{"0":1496.08837890625,"1":192.4403839111328},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":3,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":1,"type":"Joy_caption_two","pos":{"0":1004.33251953125,"1":183.7877960205078},"size":{"0":315,"1":126},"flags":{},"order":2,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":1,"label":"JoyCaptionTwo"},{"name":"image","type":"IMAGE","link":2,"label":"图像"}],"outputs":[{"name":"STRING","type":"STRING","links":[3,4],"slot_index":0,"label":"提示词"}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","long",false]},{"id":6,"type":"ShowText|pysssss","pos":{"0":1485.99365234375,"1":374.1448974609375},"size":{"0":315,"1":58},"flags":{},"order":5,"mode":0,"inputs":[{"name":"text","type":"STRING","link":5,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":5,"type":"DeepTranslatorTextNode","pos":{"0":1151,"1":410},"size":[210,285],"flags":{},"order":4,"mode":0,"inputs":[{"name":"text","type":"STRING","link":4,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"text","type":"STRING","links":[5],"slot_index":0,"label":"文本"}],"properties":{"Node name for S&R":"DeepTranslatorTextNode"},"widgets_values":["auto","chinese (simplified)",false,"","","GoogleTranslator","","proxy_hide","authorization_hide",true,true,true]}],"links":[[1,2,0,1,0,"JoyTwoPipeline"],[2,3,0,1,1,"IMAGE"],[3,1,0,4,0,"STRING"],[4,1,0,5,0,"STRING"],[5,5,0,6,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8390545288824095,"offset":[-191.4652086543963,19.226430375560426]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by xiuyidesign** [comment]
已解决
从秋叶管理器中的高级选项，打开命令提示符，![image](https://github.com/user-attachments/assets/5898bf16-dc9c-4cc3-b8a5-932fac9fb4df)
输入代码pip install accelerate==0.26.0
安装指定库，即可解决问题

**Comment by qyyxm99** [comment]
非常感谢，已经解决！
