### ISSUE TITLE
'NoneType' object has no attribute 'clear_gpu'

### ISSUE THREAD

**Issue by yy1844** [EvilBT/ComfyUI_SLK_joy_caption_two#63]
# ComfyUI Error Report
## Error Details
- **Node Type:** Batch_joy_caption_two
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'clear_gpu'
## Stack Trace
```
  File "D:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 770, in generate
    joy_two_pipeline.llm.clear_gpu(low_vram)

```
## System Information
- **ComfyUI Version:** v0.2.6-8-gee8abf0
- **Arguments:** D:\ComfyUI-aki-v1.4\main.py --auto-launch --dont-upcast-attention --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA L40S : native
  - **Type:** cuda
  - **VRAM Total:** 51175096320
  - **VRAM Free:** 50588418048
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-11 23:33:27,651 - root - INFO - Total VRAM 48804 MB, total RAM 523939 MB
2024-11-11 23:33:27,651 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-11 23:33:30,445 - root - INFO - xformers version: 0.0.27
2024-11-11 23:33:30,446 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-11 23:33:30,446 - root - INFO - Device: cuda:0 NVIDIA L40S : native
2024-11-11 23:33:31,254 - root - INFO - Using xformers cross attention
2024-11-11 23:33:33,361 - root - INFO - [Prompt Server] web root: D:\ComfyUI-aki-v1.4\web
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path checkpoints D:\sd-webui-aki-v4.9\models/Stable-diffusion
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path configs D:\sd-webui-aki-v4.9\models/Stable-diffusion
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path vae D:\sd-webui-aki-v4.9\models/VAE
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path loras D:\sd-webui-aki-v4.9\models/Lora
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path loras D:\sd-webui-aki-v4.9\models/LyCORIS
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path upscale_models D:\sd-webui-aki-v4.9\models/ESRGAN
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path upscale_models D:\sd-webui-aki-v4.9\models/RealESRGAN
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path upscale_models D:\sd-webui-aki-v4.9\models/SwinIR
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path embeddings D:\sd-webui-aki-v4.9\embeddings
2024-11-11 23:33:33,364 - root - INFO - Adding extra search path hypernetworks D:\sd-webui-aki-v4.9\models/hypernetworks
2024-11-11 23:33:33,365 - root - INFO - Adding extra search path controlnet D:\sd-webui-aki-v4.9\models/ControlNet
2024-11-11 23:33:38,200 - root - INFO - Total VRAM 48804 MB, total RAM 523939 MB
2024-11-11 23:33:38,200 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-11 23:33:38,200 - root - INFO - xformers version: 0.0.27
2024-11-11 23:33:38,200 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-11 23:33:38,200 - root - INFO - Device: cuda:0 NVIDIA L40S : native
2024-11-11 23:33:42,445 - root - INFO - --------------
2024-11-11 23:33:42,446 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-11 23:33:42,449 - root - INFO - ChatGPT.available False
2024-11-11 23:33:42,450 - root - INFO - edit_mask.available True
2024-11-11 23:33:43,966 - root - INFO - ClipInterrogator.available True
2024-11-11 23:33:44,346 - root - INFO - PromptGenerate.available True
2024-11-11 23:33:44,346 - root - INFO - ChinesePrompt.available True
2024-11-11 23:33:44,346 - root - INFO - RembgNode_.available True
2024-11-11 23:33:45,375 - root - INFO - TripoSR.available
2024-11-11 23:33:45,376 - root - INFO - MiniCPMNode.available
2024-11-11 23:33:45,881 - root - INFO - Scenedetect.available
2024-11-11 23:33:46,061 - root - INFO - FishSpeech.available
2024-11-11 23:33:46,064 - root - INFO - SenseVoice.available False
2024-11-11 23:33:46,451 - root - INFO - Whisper.available False
2024-11-11 23:33:46,470 - root - INFO - FalVideo.available
2024-11-11 23:33:46,470 - root - INFO - [93m -------------- [0m
2024-11-11 23:34:07,464 - root - INFO - 
Import times for custom nodes:
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\asymmetric-tiling-comfyui
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\websocket_image_save.py
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\tiled_ksampler
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\FreeU_Advanced
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui_otonx_nodes
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\cg-use-everywhere
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_TiledKSampler
2024-11-11 23:34:07,465 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\stability-ComfyUI-nodes
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_HF_Servelress_Inference
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\masquerade-nodes-comfyui
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-eesahesNodes
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_experiments
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\PowerNoiseSuite
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui-inpaint-nodes
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\images-grid-comfy-plugin
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\antrobots-comfyUI-nodepack
2024-11-11 23:34:07,466 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfy-image-saver
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-CUP
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Custom-Scripts
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_essentials
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\efficiency-nodes-comfyui
2024-11-11 23:34:07,467 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
2024-11-11 23:34:07,467 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui-workspace-manager
2024-11-11 23:34:07,467 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MimicMotionWrapper
2024-11-11 23:34:07,467 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-11 23:34:07,467 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-11 23:34:07,467 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui_controlnet_aux
2024-11-11 23:34:07,468 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfy_mtb
2024-11-11 23:34:07,468 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspire-Pack
2024-11-11 23:34:07,468 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
2024-11-11 23:34:07,468 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Crystools
2024-11-11 23:34:07,468 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\PuLID_ComfyUI
2024-11-11 23:34:07,468 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Long-CLIP
2024-11-11 23:34:07,468 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui_segment_anything
2024-11-11 23:34:07,468 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-KJNodes
2024-11-11 23:34:07,468 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\eden_comfy_pipelines
2024-11-11 23:34:07,468 - root - INFO -    0.3 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_LayerStyle
2024-11-11 23:34:07,468 - root - INFO -    0.8 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-11-11 23:34:07,468 - root - INFO -    0.9 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_FizzNodes
2024-11-11 23:34:07,468 - root - INFO -    1.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager
2024-11-11 23:34:07,469 - root - INFO -    1.0 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-SUPIR
2024-11-11 23:34:07,469 - root - INFO -    1.1 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack
2024-11-11 23:34:07,469 - root - INFO -    1.9 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Easy-Use
2024-11-11 23:34:07,469 - root - INFO -    6.6 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-11 23:34:07,469 - root - INFO -    6.8 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes
2024-11-11 23:34:07,469 - root - INFO -   10.4 seconds: D:\ComfyUI-aki-v1.4\custom_nodes\was-node-suite-comfyui
2024-11-11 23:34:07,469 - root - INFO - 
2024-11-11 23:34:07,503 - root - INFO - Starting server

2024-11-11 23:34:07,505 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-11 23:36:02,127 - root - INFO - got prompt
2024-11-11 23:36:16,386 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:16,387 - root - INFO - Loading 1 new model
2024-11-11 23:36:16,516 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:17,181 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:17,181 - root - INFO - Loading 1 new model
2024-11-11 23:36:17,279 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:18,142 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:18,143 - root - INFO - Loading 1 new model
2024-11-11 23:36:18,452 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:18,477 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:18,477 - root - INFO - Loading 1 new model
2024-11-11 23:36:18,483 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:18,880 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:18,881 - root - INFO - Loading 1 new model
2024-11-11 23:36:19,035 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:19,067 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:19,068 - root - INFO - Loading 1 new model
2024-11-11 23:36:19,073 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:19,580 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:19,580 - root - INFO - Loading 1 new model
2024-11-11 23:36:19,830 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:19,887 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:19,888 - root - INFO - Loading 1 new model
2024-11-11 23:36:19,895 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:20,269 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:20,270 - root - INFO - Loading 1 new model
2024-11-11 23:36:20,429 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:20,454 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:20,454 - root - INFO - Loading 1 new model
2024-11-11 23:36:20,463 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:20,838 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:20,838 - root - INFO - Loading 1 new model
2024-11-11 23:36:20,995 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:21,019 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:21,019 - root - INFO - Loading 1 new model
2024-11-11 23:36:21,026 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:21,418 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:21,418 - root - INFO - Loading 1 new model
2024-11-11 23:36:21,577 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:21,787 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:21,787 - root - INFO - Loading 1 new model
2024-11-11 23:36:21,803 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:22,271 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:22,271 - root - INFO - Loading 1 new model
2024-11-11 23:36:22,432 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:22,458 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:22,458 - root - INFO - Loading 1 new model
2024-11-11 23:36:22,463 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:22,840 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:22,840 - root - INFO - Loading 1 new model
2024-11-11 23:36:23,000 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:23,025 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:23,025 - root - INFO - Loading 1 new model
2024-11-11 23:36:23,031 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:23,428 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:23,428 - root - INFO - Loading 1 new model
2024-11-11 23:36:23,753 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:23,792 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:23,792 - root - INFO - Loading 1 new model
2024-11-11 23:36:23,797 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:24,199 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:24,199 - root - INFO - Loading 1 new model
2024-11-11 23:36:24,361 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:24,385 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:24,386 - root - INFO - Loading 1 new model
2024-11-11 23:36:24,391 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:24,775 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:24,775 - root - INFO - Loading 1 new model
2024-11-11 23:36:24,949 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:25,229 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:25,229 - root - INFO - Loading 1 new model
2024-11-11 23:36:25,276 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:25,812 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:25,812 - root - INFO - Loading 1 new model
2024-11-11 23:36:25,970 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:25,995 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:25,995 - root - INFO - Loading 1 new model
2024-11-11 23:36:26,001 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:26,381 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:26,382 - root - INFO - Loading 1 new model
2024-11-11 23:36:26,545 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:26,570 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:26,570 - root - INFO - Loading 1 new model
2024-11-11 23:36:26,575 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:26,974 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:26,974 - root - INFO - Loading 1 new model
2024-11-11 23:36:27,287 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:27,318 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:27,318 - root - INFO - Loading 1 new model
2024-11-11 23:36:27,323 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:27,727 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:27,728 - root - INFO - Loading 1 new model
2024-11-11 23:36:27,889 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:27,914 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:27,914 - root - INFO - Loading 1 new model
2024-11-11 23:36:27,920 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:28,303 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:28,303 - root - INFO - Loading 1 new model
2024-11-11 23:36:28,461 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:28,646 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:28,647 - root - INFO - Loading 1 new model
2024-11-11 23:36:28,672 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:29,120 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:29,120 - root - INFO - Loading 1 new model
2024-11-11 23:36:29,280 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:29,304 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:29,304 - root - INFO - Loading 1 new model
2024-11-11 23:36:29,310 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:29,697 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:29,697 - root - INFO - Loading 1 new model
2024-11-11 23:36:29,858 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:29,882 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:29,882 - root - INFO - Loading 1 new model
2024-11-11 23:36:29,888 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:30,282 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:30,282 - root - INFO - Loading 1 new model
2024-11-11 23:36:30,610 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:30,635 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:30,635 - root - INFO - Loading 1 new model
2024-11-11 23:36:30,641 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:31,141 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:31,141 - root - INFO - Loading 1 new model
2024-11-11 23:36:31,397 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:31,422 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:31,422 - root - INFO - Loading 1 new model
2024-11-11 23:36:31,428 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:31,878 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:31,878 - root - INFO - Loading 1 new model
2024-11-11 23:36:32,032 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:32,056 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:32,057 - root - INFO - Loading 1 new model
2024-11-11 23:36:32,062 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:32,460 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:32,460 - root - INFO - Loading 1 new model
2024-11-11 23:36:32,622 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:32,647 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:32,647 - root - INFO - Loading 1 new model
2024-11-11 23:36:32,653 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:33,165 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:33,179 - root - INFO - Loading 1 new model
2024-11-11 23:36:33,406 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:33,438 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:33,439 - root - INFO - Loading 1 new model
2024-11-11 23:36:33,444 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:33,821 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:33,821 - root - INFO - Loading 1 new model
2024-11-11 23:36:33,986 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:34,011 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:34,011 - root - INFO - Loading 1 new model
2024-11-11 23:36:34,017 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:34,393 - root - INFO - Requested to load SiglipVisionTransformer
2024-11-11 23:36:34,393 - root - INFO - Loading 1 new model
2024-11-11 23:36:34,601 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-11-11 23:36:34,777 - root - INFO - Requested to load ImageAdapter
2024-11-11 23:36:34,777 - root - INFO - Loading 1 new model
2024-11-11 23:36:34,789 - root - INFO - loaded completely 0.0 41.0390625 True
2024-11-11 23:36:35,198 - root - ERROR - !!! Exception during processing !!! 'NoneType' object has no attribute 'clear_gpu'
2024-11-11 23:36:35,200 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 770, in generate
    joy_two_pipeline.llm.clear_gpu(low_vram)
AttributeError: 'NoneType' object has no attribute 'clear_gpu'

2024-11-11 23:36:35,201 - root - INFO - Prompt executed in 33.07 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":18,"last_link_id":21,"nodes":[{"id":14,"type":"ShowText|pysssss","pos":{"0":1127,"1":104},"size":{"0":303.33282470703125,"1":163.33340454101562},"flags":{},"order":4,"mode":0,"inputs":[{"name":"text","type":"STRING","link":21,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"slot_index":0,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":17,"type":"Batch_joy_caption_two","pos":{"0":1571.806884765625,"1":458.8478698730469},"size":{"0":315,"1":154},"flags":{},"order":0,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":null,"label":"JoyCaptionTwo"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"label":"处理结果"}],"properties":{"Node name for S&R":"Batch_joy_caption_two"},"widgets_values":["","","Descriptive","long",false]},{"id":9,"type":"Joy_extra_options","pos":{"0":23,"1":218},"size":{"0":707.6665649414062,"1":460.00006103515625},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"Extra_Options","type":"Extra_Options","links":[],"slot_index":0,"label":"附加选项"}],"properties":{"Node name for S&R":"Joy_extra_options"},"widgets_values":[true,true,false,false,false,false,false,false,true,false,false,true,true,false,true,false,false]},{"id":18,"type":"Batch_joy_caption_two","pos":{"0":728,"1":31},"size":{"0":315,"1":154},"flags":{},"order":3,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":20,"label":"JoyCaptionTwo"}],"outputs":[{"name":"STRING","type":"STRING","links":[21],"label":"处理结果","slot_index":0}],"properties":{"Node name for S&R":"Batch_joy_caption_two"},"widgets_values":["D:\\lora-scripts-v1.9.0-cu124\\train\\5_xulan","D:\\lora-scripts-v1.9.0-cu124\\train\\5_xulan","Descriptive","very long",false]},{"id":2,"type":"Joy_caption_two_load","pos":{"0":47,"1":96},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[20],"slot_index":0,"label":"JoyCaptionTwo"}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct"]}],"links":[[20,2,0,18,0,"JoyTwoPipeline"],[21,18,0,14,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9646149645000006,"offset":[127.31666707597391,180.7855886020722]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by yy1844** [comment]
无论是普通的批量batch_joy，还是高级batch_joy，都是一样的报错。
python3.12.6，win11，
