### ISSUE TITLE
报错clip_model.pt缺失

### ISSUE THREAD

**Issue by shan1285** [EvilBT/ComfyUI_SLK_joy_caption_two#64]
# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 4792471536
  - **Torch VRAM Total:** 6945767424
  - **Torch VRAM Free:** 2576368

## Logs
```
2024-11-15 11:13:42,513 - root - INFO - Total VRAM 12288 MB, total RAM 32581 MB
2024-11-15 11:13:42,513 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-15 11:13:42,514 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-15 11:13:42,514 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-11-15 11:13:53,279 - root - INFO - Using pytorch cross attention
2024-11-15 11:14:05,515 - root - INFO - [Prompt Server] web root: D:\AICG\ComfyUI_windows_portable\ComfyUI\web
2024-11-15 11:14:29,553 - dinov2 - WARNING - xFormers not available
2024-11-15 11:14:29,568 - dinov2 - WARNING - xFormers not available
2024-11-15 11:14:30,572 - root - INFO - Total VRAM 12288 MB, total RAM 32581 MB
2024-11-15 11:14:30,573 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-15 11:14:30,574 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-15 11:14:30,575 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-11-15 11:14:37,136 - root - INFO - --------------
2024-11-15 11:14:37,137 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-15 11:14:37,200 - root - INFO - ChatGPT.available True
2024-11-15 11:14:37,201 - root - INFO - edit_mask.available True
2024-11-15 11:14:37,651 - root - INFO - ClipInterrogator.available True
2024-11-15 11:14:37,864 - root - INFO - PromptGenerate.available True
2024-11-15 11:14:37,864 - root - INFO - ChinesePrompt.available True
2024-11-15 11:14:37,864 - root - INFO - RembgNode_.available True
2024-11-15 11:14:40,008 - root - INFO - TripoSR.available
2024-11-15 11:14:40,009 - root - INFO - MiniCPMNode.available
2024-11-15 11:14:43,098 - root - INFO - Scenedetect.available
2024-11-15 11:14:43,387 - root - INFO - FishSpeech.available
2024-11-15 11:14:43,401 - root - INFO - SenseVoice.available False
2024-11-15 11:14:44,197 - root - INFO - Whisper.available False
2024-11-15 11:14:44,247 - root - INFO - FalVideo.available
2024-11-15 11:14:44,248 - root - INFO - [93m -------------- [0m
2024-11-15 11:14:51,550 - py.warnings - WARNING - D:\AICG\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchmetrics\utilities\prints.py:43: UserWarning: Metric `InceptionScore` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)  # noqa: B028

2024-11-15 11:15:23,753 - root - INFO - 
Import times for custom nodes:
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-11-15 11:15:23,754 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native-main
2024-11-15 11:15:23,755 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-11-15 11:15:23,755 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main
2024-11-15 11:15:23,755 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-15 11:15:23,755 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main
2024-11-15 11:15:23,756 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-copilot
2024-11-15 11:15:23,756 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
2024-11-15 11:15:23,756 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-15 11:15:23,756 - root - INFO -    0.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3d-photo-inpainting
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper-main
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes-main
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-15 11:15:23,756 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-11-15 11:15:23,757 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-11-15 11:15:23,757 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2-main
2024-11-15 11:15:23,757 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-11-15 11:15:23,757 - root - INFO -    0.1 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR-main
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack-main
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-15 11:15:23,757 - root - INFO -    0.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-15 11:15:23,757 - root - INFO -    0.3 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-15 11:15:23,757 - root - INFO -    0.4 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ollama
2024-11-15 11:15:23,757 - root - INFO -    0.4 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-11-15 11:15:23,757 - root - INFO -    0.5 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node-main
2024-11-15 11:15:23,757 - root - INFO -    0.6 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-15 11:15:23,757 - root - INFO -    0.7 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use-main
2024-11-15 11:15:23,757 - root - INFO -    0.8 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\RealisDance-ComfyUI
2024-11-15 11:15:23,757 - root - INFO -    1.3 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UniAnimate
2024-11-15 11:15:23,757 - root - INFO -    1.3 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main
2024-11-15 11:15:23,758 - root - INFO -    1.5 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui-main
2024-11-15 11:15:23,758 - root - INFO -    1.5 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle-main
2024-11-15 11:15:23,758 - root - INFO -    1.6 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-15 11:15:23,758 - root - INFO -    1.8 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-11-15 11:15:23,758 - root - INFO -    2.0 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OllamaGemini
2024-11-15 11:15:23,758 - root - INFO -    2.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-15 11:15:23,758 - root - INFO -    2.2 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
2024-11-15 11:15:23,758 - root - INFO -    2.3 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-11-15 11:15:23,758 - root - INFO -    5.5 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-15 11:15:23,758 - root - INFO -    6.8 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-11-15 11:15:23,758 - root - INFO -   12.8 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-11-15 11:15:23,758 - root - INFO -   19.5 seconds: D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF-main
2024-11-15 11:15:23,758 - root - INFO - 
2024-11-15 11:15:23,775 - root - INFO - Starting server

2024-11-15 11:15:23,776 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-15 11:15:53,122 - root - INFO - got prompt
2024-11-15 11:15:53,311 - dinov2 - INFO - using MLP layer as FFN
2024-11-15 11:16:13,373 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-11-15 11:16:13,373 - root - INFO - model_type FLUX
2024-11-15 11:18:35,483 - root - INFO - Using pytorch attention in VAE
2024-11-15 11:18:35,484 - root - INFO - Using pytorch attention in VAE
2024-11-15 11:21:04,117 - root - INFO - Requested to load AutoencodingEngine
2024-11-15 11:21:04,145 - root - INFO - Loading 1 new model
2024-11-15 11:21:04,726 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-11-15 11:23:22,857 - root - INFO - Requested to load FluxClipModel_
2024-11-15 11:23:22,956 - root - INFO - Loading 1 new model
2024-11-15 11:23:27,456 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-11-15 11:25:21,788 - root - ERROR - !!! Exception during processing !!! 
2024-11-15 11:25:21,875 - root - ERROR - Traceback (most recent call last):
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 268, in generate
    self.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-11-15 11:25:21,905 - root - INFO - Prompt executed in 568.78 seconds
2024-11-15 11:25:30,020 - root - INFO - got prompt
2024-11-15 11:25:32,238 - root - ERROR - !!! Exception during processing !!! 
2024-11-15 11:25:32,239 - root - ERROR - Traceback (most recent call last):
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-11-15 11:25:32,255 - root - INFO - Prompt executed in 2.06 seconds
2024-11-15 11:38:03,226 - root - INFO - got prompt
2024-11-15 11:38:04,204 - root - ERROR - !!! Exception during processing !!! 
2024-11-15 11:38:04,205 - root - ERROR - Traceback (most recent call last):
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AICG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two-main\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-11-15 11:38:04,206 - root - INFO - Prompt executed in 0.97 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by xingzhaoyang** [comment]
我也是这个错误，不知道为什么？

**Comment by xingzhaoyang** [comment]
F:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-384
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 1.88 seconds

**Comment by xingzhaoyang** [comment]
我解决了， Joy_caption_two 目录名 写错了！

**Comment by jmjmeijin** [comment]
> 我解决了， Joy_caption_two 目录名写错了！

请问这是什么意思？怎么解决？

**Comment by a45709991** [comment]
在哪里改
我已经按照所有要求放置文件，还是一直报错。
