### ISSUE TITLE
通过manager安装，但还是报错找不到clip_model.pt

### ISSUE THREAD

**Issue by yvonnehoo** [EvilBT/ComfyUI_SLK_joy_caption_two#73]
求助大佬，我在COLAB上跑的comfyui，直接通过Manager一键安装，为什么还是报错呢

# ComfyUI Error Report
## Error Details
- **Node ID:** 13
- **Node Type:** Joy_caption_two_load
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 268, in generate
    self.loadModels()

  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()

  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)

  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()

```
## System Information
- **ComfyUI Version:** v0.3.4-8-g15c39ea
- **Arguments:** main.py --dont-print-server
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.0+cu121
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15835660288
  - **VRAM Free:** 15727656960
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-26T14:40:07.312956 - [START] Security scan2024-11-26T14:40:07.312978 - 
2024-11-26T14:40:08.282914 - [DONE] Security scan2024-11-26T14:40:08.282935 - 
2024-11-26T14:40:08.372748 - ## ComfyUI-Manager: installing dependencies done.2024-11-26T14:40:08.372886 - 
2024-11-26T14:40:08.372960 - ** ComfyUI startup time:2024-11-26T14:40:08.373027 -  2024-11-26T14:40:08.373090 - 2024-11-26 14:40:08.3729002024-11-26T14:40:08.373170 - 
2024-11-26T14:40:08.373239 - ** Platform:2024-11-26T14:40:08.373304 -  2024-11-26T14:40:08.373360 - Linux2024-11-26T14:40:08.373422 - 
2024-11-26T14:40:08.373483 - ** Python version:2024-11-26T14:40:08.373546 -  2024-11-26T14:40:08.373611 - 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]2024-11-26T14:40:08.373671 - 
2024-11-26T14:40:08.373731 - ** Python executable:2024-11-26T14:40:08.373791 -  2024-11-26T14:40:08.373851 - /usr/bin/python32024-11-26T14:40:08.373928 - 
2024-11-26T14:40:08.373988 - ** ComfyUI Path:2024-11-26T14:40:08.374047 -  2024-11-26T14:40:08.374106 - /content/drive/MyDrive/AI/ComfyUI2024-11-26T14:40:08.374165 - 
2024-11-26T14:40:08.374244 - ** Log path:2024-11-26T14:40:08.374302 -  2024-11-26T14:40:08.374362 - /content/drive/MyDrive/AI/ComfyUI/comfyui.log2024-11-26T14:40:08.374421 - 
2024-11-26T14:40:09.779785 - 
Prestartup times for custom nodes:2024-11-26T14:40:09.779883 - 
2024-11-26T14:40:09.779954 -    2.5 seconds:2024-11-26T14:40:09.780010 -  2024-11-26T14:40:09.780063 - /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Manager2024-11-26T14:40:09.780114 - 
2024-11-26T14:40:09.780169 - 
2024-11-26T14:40:11.563810 - Total VRAM 15102 MB, total RAM 52217 MB
2024-11-26T14:40:11.564184 - pytorch version: 2.1.0+cu121
2024-11-26T14:40:11.566701 - WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-11-26T14:40:12.373614 - xformers version: 0.0.22.post4+cu118
2024-11-26T14:40:12.374007 - Set vram state to: NORMAL_VRAM
2024-11-26T14:40:12.374200 - Device: cuda:0 Tesla T4 : cudaMallocAsync
2024-11-26T14:40:13.193987 - Using pytorch cross attention
2024-11-26T14:40:14.061425 - [Prompt Server] web root: /content/drive/MyDrive/AI/ComfyUI/web
2024-11-26T14:40:14.740014 - ### Loading: ComfyUI-Manager (V2.52)2024-11-26T14:40:14.740119 - 
2024-11-26T14:40:16.545962 - ### ComfyUI Revision: 2862 [15c39ea7] | Released on '2024-11-26'2024-11-26T14:40:16.546069 - 
2024-11-26T14:40:16.593060 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-26T14:40:16.593163 - 
2024-11-26T14:40:16.603062 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-26T14:40:16.603289 - 
2024-11-26T14:40:16.623167 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-26T14:40:16.623778 - 
2024-11-26T14:40:16.669918 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-26T14:40:16.670010 - 
2024-11-26T14:40:16.705094 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-26T14:40:16.705200 - 
2024-11-26T14:40:16.761392 - [AnimateDiffEvo] - [0;31mERROR[0m - No motion models found. Please download one and place in: ['/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/models', '/content/drive/MyDrive/AI/ComfyUI/models/animatediff_models']
2024-11-26T14:40:16.791514 - [1;35m### [START] ComfyUI AlekPet Nodes [1;34mv1.0.35[0m[1;35m ###[0m2024-11-26T14:40:16.791662 - 
2024-11-26T14:40:18.362788 - [92mNode -> ChatGLMNode: [93mChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode[0m [92m[Loading] [0m2024-11-26T14:40:18.363834 - 
2024-11-26T14:40:18.437977 - [92mNode -> ArgosTranslateNode: [93mArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode[0m [92m[Loading] [0m2024-11-26T14:40:18.438352 - 
2024-11-26T14:40:18.446953 - [92mNode -> GoogleTranslateNode: [93mGoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode[0m [92m[Loading] [0m2024-11-26T14:40:18.455378 - 
2024-11-26T14:40:18.464992 - [92mNode -> DeepTranslatorNode: [93mDeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode[0m [92m[Loading] [0m2024-11-26T14:40:18.467668 - 
2024-11-26T14:40:18.561287 - [92mNode -> PoseNode: [93mPoseNode[0m [92m[Loading] [0m2024-11-26T14:40:18.563197 - 
2024-11-26T14:40:18.578976 - [92mNode -> ExtrasNode: [93mPreviewTextNode, HexToHueNode, ColorsCorrectNode[0m [92m[Loading] [0m2024-11-26T14:40:18.579283 - 
2024-11-26T14:40:20.044651 - [92mNode -> IDENode: [93mIDENode[0m [92m[Loading] [0m2024-11-26T14:40:20.047093 - 
2024-11-26T14:40:23.525801 - [92mNode -> PainterNode: [93mPainterNode[0m [92m[Loading] [0m2024-11-26T14:40:23.525959 - 
2024-11-26T14:40:23.526416 - [1;35m### [END] ComfyUI AlekPet Nodes ###[0m2024-11-26T14:40:23.526533 - 
2024-11-26T14:40:23.939341 - 
Import times for custom nodes:
2024-11-26T14:40:23.939553 -    0.0 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-26T14:40:23.939670 -    0.0 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
2024-11-26T14:40:23.939802 -    0.1 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two
2024-11-26T14:40:23.939924 -    0.2 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
2024-11-26T14:40:23.940029 -    1.8 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-26T14:40:23.940118 -    7.1 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
2024-11-26T14:40:23.940201 - 
2024-11-26T14:40:23.953512 - Starting server

2024-11-26T14:40:23.953950 - To see the GUI go to: http://127.0.0.1:8188
2024-11-26T14:42:15.212685 - FETCH DATA from: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-11-26T14:42:15.212739 - 2024-11-26T14:42:15.222002 -  [DONE]2024-11-26T14:42:15.222132 - 
2024-11-26T14:44:59.657640 - got prompt
2024-11-26T14:44:59.662221 - Failed to validate prompt for output 14:
2024-11-26T14:44:59.662451 - * Joy_caption_two_advanced 11:
2024-11-26T14:44:59.662563 -   - Required input is missing: extra_options
2024-11-26T14:44:59.662660 - Output will be ignored
2024-11-26T14:44:59.662776 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-26T14:45:37.600360 - got prompt
2024-11-26T14:45:37.628996 - /content/drive/MyDrive/AI/ComfyUI/models/clip/siglip-so400m-patch14-3842024-11-26T14:45:37.629119 - 
2024-11-26T14:45:40.193806 - NumExpr defaulting to 8 threads.
2024-11-26T14:45:43.341312 - !!! Exception during processing !!! 
2024-11-26T14:45:43.347370 - Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/drive/MyDrive/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 268, in generate
    self.loadModels()
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
AssertionError

2024-11-26T14:45:43.348690 - Prompt executed in 5.74 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":16,"last_link_id":16,"nodes":[{"id":14,"type":"PreviewTextNode","pos":[1198.9781494140625,96.77291107177734],"size":[210,58],"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":16,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":null,"label":"STRING"}],"properties":{"Node name for S&R":"PreviewTextNode"},"widgets_values":["","",[false,true]]},{"id":16,"type":"Joy_caption_two","pos":[812,48],"size":[315,126],"flags":{},"order":2,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":14,"label":"joy_two_pipeline"},{"name":"image","type":"IMAGE","link":15,"label":"image"}],"outputs":[{"name":"STRING","type":"STRING","links":[16],"label":"STRING","slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","long",false]},{"id":12,"type":"LoadImage","pos":[300,61],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[15],"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["cat.jpg","image"]},{"id":13,"type":"Joy_caption_two_load","pos":[282,-79],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[14],"label":"JoyTwoPipeline","slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]}],"links":[[14,13,0,16,0,"JoyTwoPipeline"],[15,12,0,16,1,"IMAGE"],[16,16,0,14,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":{"0":180.61224365234375,"1":376.279052734375}}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by EvilBT** [comment]
有一个模型要手动下载的，你仔细阅读一下文档

**Comment by wfuliman** [comment]
解决了嘛，哥？我也是报错缺少clip_model_pt，但是下载了的，存在的。

**Comment by Astroburner** [comment]
There is a error in the code: 
`clip_model = clip_model.vision_model

        assert (BASE_MODEL_PATH / "clip_model.pt").exists()
        print("Loading VLM's custom vision model")
        checkpoint = torch.load(**_BASE_MODEL_PATH / "clip_model.pt"_**, map_location='cpu', weights_only=True)
        checkpoint = {k.replace("_orig_mod.module.", ""): v for k, v in checkpoint.items()}
        clip_model.load_state_dict(checkpoint)
        del checkpoint"`
        
ComfyUI>models>clip>siglip-so400m-patch14-384 =
.gitattributes
config.json
model.safetensors
preprocessor_config.json
README.md
special_tokens_map.json
spiece.model
tokenizer.json
tokenizer_config.json

I would ask you kindly to check your installation describtion: 
- the model you linked and said we should download has no "clip_model.pt" file.

A: 
change the code to =
`clip_model = clip_model.vision_model

assert (BASE_MODEL_PATH / "clip_model.pt").exists() or (BASE_MODEL_PATH / "clip_model.safetensors").exists()
print("Loading VLM's custom vision model")

if (BASE_MODEL_PATH / "clip_model.pt").exists():
    checkpoint = torch.load(BASE_MODEL_PATH / "clip_model.pt", map_location='cpu', weights_only=True)
elif (BASE_MODEL_PATH / "clip_model.safetensors").exists():
    from safetensors.torch import load_file  # Safetensors muss installiert sein
    checkpoint = load_file(BASE_MODEL_PATH / "clip_model.safetensors")

checkpoint = {k.replace("_orig_mod.module.", ""): v for k, v in checkpoint.items()}

clip_model.load_state_dict(checkpoint)
del checkpoint`

Result:
Next error: 
`E:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-384
!!! Exception during processing !!! Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-384.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 469, in generate
    joy_two_pipeline.parent.loadModels()
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 277, in loadModels
    self.pipeline.loadModels()
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 243, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 43, in __init__
    clip_model = AutoModel.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3504, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-384.`
