### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maiqunshan** [EvilBT/ComfyUI_SLK_joy_caption_two#79]
got prompt
C:\ComfyUI_MAI\ComfyUI\models\clip\siglip-so400m-patch14-384
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_MAI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 268, in generate
    self.loadModels()
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
AssertionError

Prompt executed in 2.02 seconds

**Comment by andy2025gogo** [comment]
我也是遇到同样的问题，求解

**Comment by EvilBT** [comment]
请仔细阅读readmd.md文档，特别是关于模型下载保存到相关目录那部分，保存到哪里看了readme.md还是不清楚的，可以反馈给我，我更新一下
