### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'clear_gpu'

### ISSUE THREAD

**Issue by lestersssss** [EvilBT/ComfyUI_SLK_joy_caption_two#83]
got prompt
E:\ComfyUI-aki-v1.4\models\clip\siglip-so400m-patch14-384
Loading VLM's custom vision model
Prompt: Write a descriptive caption for this image in a formal tone within 80 words. Do NOT mention the image's resolution. Do NOT use any ambiguous language. ONLY describe the most important elements of the image.
!!! Exception during processing !!! 'NoneType' object has no attribute 'clear_gpu'
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.4\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 989, in generate
    joy_two_pipeline.llm.clear_gpu(low_vram)
AttributeError: 'NoneType' object has no attribute 'clear_gpu'

Prompt executed in 2.77 seconds

**Comment by NurdVybe** [comment]
I'm having the exact same issue. Anyone figure this out?

**Comment by sp1ffyparsley** [comment]
same issue any solution?
