### ISSUE TITLE
Joy_caption_two报错

### ISSUE THREAD

**Issue by yujingzhi** [EvilBT/ComfyUI_SLK_joy_caption_two#86]
# ComfyUI Error Report
## Error Details
- **Node ID:** 13
- **Node Type:** Joy_caption_two
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.6-10-gf7695b5
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 15964569600
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-12-12T01:20:40.370875 - [START] Security scan2024-12-12T01:20:40.370875 - 
2024-12-12T01:20:41.072411 - [DONE] Security scan2024-12-12T01:20:41.072411 - 
2024-12-12T01:20:41.174482 - ## ComfyUI-Manager: installing dependencies done.2024-12-12T01:20:41.174482 - 
2024-12-12T01:20:41.174482 - ** ComfyUI startup time:2024-12-12T01:20:41.175482 -  2024-12-12T01:20:41.175482 - 2024-12-12 01:20:41.1744822024-12-12T01:20:41.175482 - 
2024-12-12T01:20:41.194482 - ** Platform:2024-12-12T01:20:41.194482 -  2024-12-12T01:20:41.194482 - Windows2024-12-12T01:20:41.194482 - 
2024-12-12T01:20:41.194482 - ** Python version:2024-12-12T01:20:41.195482 -  2024-12-12T01:20:41.195482 - 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]2024-12-12T01:20:41.195482 - 
2024-12-12T01:20:41.195482 - ** Python executable:2024-12-12T01:20:41.195482 -  2024-12-12T01:20:41.195482 - D:\ComfyUI_windows_portable\python_embeded\python.exe2024-12-12T01:20:41.195482 - 
2024-12-12T01:20:41.195482 - ** ComfyUI Path:2024-12-12T01:20:41.195482 -  2024-12-12T01:20:41.195482 - D:\ComfyUI_windows_portable\ComfyUI2024-12-12T01:20:41.195482 - 
2024-12-12T01:20:41.195482 - ** Log path:2024-12-12T01:20:41.196482 -  2024-12-12T01:20:41.196482 - D:\ComfyUI_windows_portable\comfyui.log2024-12-12T01:20:41.196482 - 
2024-12-12T01:20:41.973774 - 
Prestartup times for custom nodes:2024-12-12T01:20:41.973774 - 
2024-12-12T01:20:41.974775 -    0.0 seconds:2024-12-12T01:20:41.975942 -  2024-12-12T01:20:41.975942 - D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy2024-12-12T01:20:41.975942 - 
2024-12-12T01:20:41.975942 -    1.6 seconds:2024-12-12T01:20:41.975942 -  2024-12-12T01:20:41.975942 - D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager2024-12-12T01:20:41.975942 - 
2024-12-12T01:20:41.975942 - 
2024-12-12T01:20:43.064440 - Total VRAM 16380 MB, total RAM 32599 MB
2024-12-12T01:20:43.065409 - pytorch version: 2.5.1+cu124
2024-12-12T01:20:43.066410 - Set vram state to: NORMAL_VRAM
2024-12-12T01:20:43.067409 - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-12T01:20:43.672658 - Using pytorch cross attention
2024-12-12T01:20:44.400780 - [Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
2024-12-12T01:20:44.685171 - xFormers not available
2024-12-12T01:20:44.686171 - xFormers not available
2024-12-12T01:20:44.833954 - Total VRAM 16380 MB, total RAM 32599 MB
2024-12-12T01:20:44.834429 - pytorch version: 2.5.1+cu124
2024-12-12T01:20:44.835465 - Set vram state to: NORMAL_VRAM
2024-12-12T01:20:44.836431 - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-12T01:20:44.874950 - ### Loading: ComfyUI-Manager (V2.55.4)2024-12-12T01:20:44.874950 - 
2024-12-12T01:20:45.062789 - ### ComfyUI Version: v0.3.6-10-gf7695b5 | Released on '2024-12-03'2024-12-12T01:20:45.062789 - 
2024-12-12T01:20:45.174299 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-12-12T01:20:45.174299 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-12T01:20:45.176310 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-12T01:20:45.356458 - [1;35m### [START] ComfyUI AlekPet Nodes [1;34mv1.0.37[0m[1;35m ###[0m2024-12-12T01:20:45.356787 - 
2024-12-12T01:20:45.526603 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-12T01:20:45.527110 - 
2024-12-12T01:20:45.683487 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-12T01:20:45.684487 - 
2024-12-12T01:20:45.697488 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-12T01:20:45.697488 - 
2024-12-12T01:20:45.710976 - [92mNode -> ChatGLMNode: [93mChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode[0m [92m[Loading] [0m2024-12-12T01:20:45.710976 - 
2024-12-12T01:20:45.712976 - [92mNode -> ArgosTranslateNode: [93mArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode[0m [92m[Loading] [0m2024-12-12T01:20:45.712976 - 
2024-12-12T01:20:45.716976 - [92mNode -> DeepTranslatorNode: [93mDeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode[0m [92m[Loading] [0m2024-12-12T01:20:45.716976 - 
2024-12-12T01:20:45.717976 - [92mNode -> GoogleTranslateNode: [93mGoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode[0m [92m[Loading] [0m2024-12-12T01:20:45.717976 - 
2024-12-12T01:20:45.720976 - [92mNode -> ExtrasNode: [93mPreviewTextNode, HexToHueNode, ColorsCorrectNode[0m [92m[Loading] [0m2024-12-12T01:20:45.721976 - 
2024-12-12T01:20:45.721976 - [92mNode -> PoseNode: [93mPoseNode[0m [92m[Loading] [0m2024-12-12T01:20:45.721976 - 
2024-12-12T01:20:45.740053 - [92mNode -> IDENode: [93mIDENode[0m [92m[Loading] [0m2024-12-12T01:20:45.740053 - 
2024-12-12T01:20:45.777588 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-12T01:20:45.777588 - 
2024-12-12T01:20:45.784183 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-12T01:20:45.784183 - 
2024-12-12T01:20:45.809153 - [92mNode -> PainterNode: [93mPainterNode[0m [92m[Loading] [0m2024-12-12T01:20:45.809706 - 
2024-12-12T01:20:45.809706 - [1;35m### [END] ComfyUI AlekPet Nodes ###[0m2024-12-12T01:20:45.809706 - 
2024-12-12T01:20:46.151772 - 
2024-12-12T01:20:46.151772 - [92m[rgthree-comfy] Loaded 42 exciting nodes. 🎉[00m2024-12-12T01:20:46.153567 - 
2024-12-12T01:20:46.153567 - 
2024-12-12T01:20:46.167109 - 
Import times for custom nodes:
2024-12-12T01:20:46.169110 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-12T01:20:46.169110 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main
2024-12-12T01:20:46.169110 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-12-12T01:20:46.169110 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-12-12T01:20:46.170108 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_JC2
2024-12-12T01:20:46.170108 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
2024-12-12T01:20:46.170108 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-12-12T01:20:46.171120 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-12-12T01:20:46.171624 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-12-12T01:20:46.171624 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-12T01:20:46.172627 -    0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux
2024-12-12T01:20:46.172627 -    0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-12T01:20:46.172627 -    0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-12T01:20:46.172627 -    0.8 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-12-12T01:20:46.173626 - 
2024-12-12T01:20:46.179626 - Starting server

2024-12-12T01:20:46.180626 - To see the GUI go to: http://127.0.0.1:8188
2024-12-12T01:20:46.732978 - FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-12T01:20:46.732978 - 2024-12-12T01:20:46.735976 -  [DONE]2024-12-12T01:20:46.735976 - 
2024-12-12T01:20:46.877006 - []2024-12-12T01:20:46.877006 - 
2024-12-12T01:20:46.877006 - []2024-12-12T01:20:46.877006 - 
2024-12-12T01:21:13.586723 - got prompt
2024-12-12T01:21:13.663351 - D:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-3842024-12-12T01:21:13.663351 - 
2024-12-12T01:21:14.803956 - !!! Exception during processing !!! 
2024-12-12T01:21:14.804956 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 268, in generate
    self.loadModels()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-12T01:21:14.807957 - Prompt executed in 1.21 seconds
2024-12-12T01:23:24.830844 - got prompt
2024-12-12T01:23:24.841976 - D:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-3842024-12-12T01:23:24.841976 - 
2024-12-12T01:23:25.826707 - !!! Exception during processing !!! 
2024-12-12T01:23:25.827707 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 300, in generate
    joy_two_pipeline.parent.loadModels()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 263, in loadModels
    self.pipeline.loadModels()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 229, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 51, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-12-12T01:23:25.830490 - Prompt executed in 0.99 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":17,"nodes":[{"id":12,"type":"ShowText|pysssss","pos":[-544.5592041015625,6116.13330078125],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":12,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":8,"type":"LoadImage","pos":[-964.9876708984375,6068.6142578125],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[14],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["prompthero-prompt-82b4410e01a.webp","image"]},{"id":15,"type":"Joy_caption_two_load","pos":[-964.6824340820312,5930.5859375],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[16],"slot_index":0,"label":"JoyCaptionTwo"}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]},{"id":13,"type":"Joy_caption_two","pos":[-549.437744140625,5924.4697265625],"size":[315,126],"flags":{},"order":2,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":16,"label":"JoyCaptionTwo"},{"name":"image","type":"IMAGE","link":14,"label":"图像"}],"outputs":[{"name":"STRING","type":"STRING","links":[12],"label":"提示词"}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","any",true]}],"links":[[12,13,0,12,0,"STRING"],[14,8,0,13,1,"IMAGE"],[16,15,0,13,0,"JoyTwoPipeline"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.083470594338842,"offset":[1684.5910409167482,-5499.568040585215]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by yujingzhi** [comment]
![joycaptiontwo报错](https://github.com/user-attachments/assets/179a2452-6a38-4409-96ff-234a21a24499)

**Comment by ymilv** [comment]
我开始也遇到一样的问题，后来发现应该是路径问题。
你检查一下“models\Joy_caption_two”文件夹的名字，clone下来默认的名字不对，另外还需要把里面的一层子文件夹去掉。变成这样才行：
![微信截图_20241213203633](https://github.com/user-attachments/assets/297bb0bd-b692-4137-a573-877e717edfe3)

**Comment by Raygens** [comment]
> 我开始也遇到一样的问题，后来发现应该是路径问题。 你检查一下“models\Joy_caption_two”文件夹的名字，clone下来默认的名字不对，另外还需要把里面的一层子文件夹去掉。变成这样才行： ![微信截图_20241213203633](https://github.com/user-attachments/assets/297bb0bd-b692-4137-a573-877e717edfe3)

那你里边那个其它那些文件包里的东西不要了吗？

**Comment by daizong9899** [comment]
我去，终于搞定了，原来就是中间横线的问题，把中横线改成下横线就行了，感谢楼里各位哥们了，总算能跑了，谢谢哈

**Comment by pongjoo** [comment]
感谢各位大神！
