### ISSUE TITLE
JoyCaptionTwo cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\errors.py)

### ISSUE THREAD

**Issue by yujingzhi** [EvilBT/ComfyUI_SLK_joy_caption_two#87]
# ComfyUI Error Report
## Error Details
- **Node ID:** 13
- **Node Type:** Joy_caption_two
- **Exception Type:** ImportError
- **Exception Message:** cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\errors.py)
## Stack Trace
```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 4310, in from_pretrained
    model.load_adapter(

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\integrations\peft.py", line 161, in load_adapter
    from peft import PeftConfig, inject_adapter_in_model, load_peft_weights

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 31, in <module>
    from .config import PeftConfig

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils\__init__.py", line 22, in <module>
    from .loftq_utils import replace_lora_weights_loftq

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils\loftq_utils.py", line 26, in <module>
    from huggingface_hub.errors import HFValidationError, LocalEntryNotFoundError

```
## System Information
- **ComfyUI Version:** v0.3.6-10-gf7695b5
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 15008325816
  - **Torch VRAM Total:** 1006632960
  - **Torch VRAM Free:** 98623672

## Logs
```
2024-12-12T10:37:49.254909 - [START] Security scan2024-12-12T10:37:49.254909 - 
2024-12-12T10:37:50.010355 - [DONE] Security scan2024-12-12T10:37:50.010355 - 
2024-12-12T10:37:50.123842 - ## ComfyUI-Manager: installing dependencies done.2024-12-12T10:37:50.123842 - 
2024-12-12T10:37:50.123842 - ** ComfyUI startup time:2024-12-12T10:37:50.123842 -  2024-12-12T10:37:50.123842 - 2024-12-12 10:37:50.1238422024-12-12T10:37:50.123842 - 
2024-12-12T10:37:50.142162 - ** Platform:2024-12-12T10:37:50.142162 -  2024-12-12T10:37:50.143165 - Windows2024-12-12T10:37:50.143165 - 
2024-12-12T10:37:50.143165 - ** Python version:2024-12-12T10:37:50.143165 -  2024-12-12T10:37:50.143165 - 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]2024-12-12T10:37:50.143165 - 
2024-12-12T10:37:50.143165 - ** Python executable:2024-12-12T10:37:50.143165 -  2024-12-12T10:37:50.143165 - D:\ComfyUI_windows_portable\python_embeded\python.exe2024-12-12T10:37:50.143165 - 
2024-12-12T10:37:50.143165 - ** ComfyUI Path:2024-12-12T10:37:50.143165 -  2024-12-12T10:37:50.143165 - D:\ComfyUI_windows_portable\ComfyUI2024-12-12T10:37:50.143165 - 
2024-12-12T10:37:50.143165 - ** Log path:2024-12-12T10:37:50.144165 -  2024-12-12T10:37:50.144165 - D:\ComfyUI_windows_portable\comfyui.log2024-12-12T10:37:50.144165 - 
2024-12-12T10:37:50.894975 - 
Prestartup times for custom nodes:2024-12-12T10:37:50.895485 - 
2024-12-12T10:37:50.895485 -    0.0 seconds:2024-12-12T10:37:50.895994 -  2024-12-12T10:37:50.895994 - D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy2024-12-12T10:37:50.895994 - 
2024-12-12T10:37:50.895994 -    1.6 seconds:2024-12-12T10:37:50.895994 -  2024-12-12T10:37:50.895994 - D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager2024-12-12T10:37:50.895994 - 
2024-12-12T10:37:50.895994 - 
2024-12-12T10:37:52.172211 - Total VRAM 16380 MB, total RAM 32599 MB
2024-12-12T10:37:52.172211 - pytorch version: 2.5.1+cu124
2024-12-12T10:37:52.173213 - Set vram state to: NORMAL_VRAM
2024-12-12T10:37:52.173213 - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-12T10:37:52.958166 - Using pytorch cross attention
2024-12-12T10:37:53.937427 - [Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
2024-12-12T10:37:54.371805 - xFormers not available
2024-12-12T10:37:54.372823 - xFormers not available
2024-12-12T10:37:54.546695 - Total VRAM 16380 MB, total RAM 32599 MB
2024-12-12T10:37:54.546695 - pytorch version: 2.5.1+cu124
2024-12-12T10:37:54.546695 - Set vram state to: NORMAL_VRAM
2024-12-12T10:37:54.547697 - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-12T10:37:54.591259 - ### Loading: ComfyUI-Manager (V2.55.4)2024-12-12T10:37:54.591259 - 
2024-12-12T10:37:54.786678 - ### ComfyUI Version: v0.3.6-10-gf7695b5 | Released on '2024-12-03'2024-12-12T10:37:54.786678 - 
2024-12-12T10:37:54.895593 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-12-12T10:37:54.896593 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-12T10:37:54.896593 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-12T10:37:55.122223 - [1;35m### [START] ComfyUI AlekPet Nodes [1;34mv1.0.37[0m[1;35m ###[0m2024-12-12T10:37:55.122223 - 
2024-12-12T10:37:55.286742 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-12T10:37:55.286742 - 
2024-12-12T10:37:55.302625 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-12T10:37:55.302625 - 
2024-12-12T10:37:55.339313 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-12T10:37:55.340313 - 
2024-12-12T10:37:55.426319 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-12T10:37:55.426319 - 
2024-12-12T10:37:55.442320 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-12T10:37:55.442320 - 
2024-12-12T10:37:55.477106 - [92mNode -> ChatGLMNode: [93mChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode[0m [92m[Loading] [0m2024-12-12T10:37:55.477106 - 
2024-12-12T10:37:55.483106 - [92mNode -> ArgosTranslateNode: [93mArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode[0m [92m[Loading] [0m2024-12-12T10:37:55.483106 - [92mNode -> DeepTranslatorNode: [93mDeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode[0m [92m[Loading] [0m2024-12-12T10:37:55.483106 - 
2024-12-12T10:37:55.483106 - 
2024-12-12T10:37:55.485106 - [92mNode -> GoogleTranslateNode: [93mGoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode[0m [92m[Loading] [0m2024-12-12T10:37:55.485106 - 
2024-12-12T10:37:55.488106 - [92mNode -> PoseNode: [93mPoseNode[0m [92m[Loading] [0m2024-12-12T10:37:55.488106 - 
2024-12-12T10:37:55.488106 - [92mNode -> ExtrasNode: [93mPreviewTextNode, HexToHueNode, ColorsCorrectNode[0m [92m[Loading] [0m2024-12-12T10:37:55.489106 - 
2024-12-12T10:37:55.519928 - [92mNode -> IDENode: [93mIDENode[0m [92m[Loading] [0m2024-12-12T10:37:55.519928 - 
2024-12-12T10:37:55.641485 - [92mNode -> PainterNode: [93mPainterNode[0m [92m[Loading] [0m2024-12-12T10:37:55.641485 - 
2024-12-12T10:37:55.642485 - [1;35m### [END] ComfyUI AlekPet Nodes ###[0m2024-12-12T10:37:55.642485 - 
2024-12-12T10:37:56.069040 - 
2024-12-12T10:37:56.069040 - [92m[rgthree-comfy] Loaded 42 epic nodes. 🎉[00m2024-12-12T10:37:56.069040 - 
2024-12-12T10:37:56.069542 - 
2024-12-12T10:37:56.087046 - 
Import times for custom nodes:
2024-12-12T10:37:56.087046 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-12T10:37:56.087046 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main
2024-12-12T10:37:56.087046 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-12-12T10:37:56.087556 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_joy-caption-alpha-two
2024-12-12T10:37:56.087556 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-12-12T10:37:56.087556 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
2024-12-12T10:37:56.087556 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-12-12T10:37:56.087556 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-12-12T10:37:56.088064 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-12-12T10:37:56.088064 -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-12T10:37:56.088064 -    0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux
2024-12-12T10:37:56.088064 -    0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-12T10:37:56.088064 -    0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-12T10:37:56.088571 -    0.9 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-12-12T10:37:56.088571 - 
2024-12-12T10:37:56.095238 - Starting server

2024-12-12T10:37:56.095238 - To see the GUI go to: http://127.0.0.1:8188
2024-12-12T10:37:56.697910 - FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-12T10:37:56.698909 - 2024-12-12T10:37:56.701911 -  [DONE]2024-12-12T10:37:56.701911 - 
2024-12-12T10:37:56.854545 - []2024-12-12T10:37:56.854545 - 
2024-12-12T10:37:56.854545 - []2024-12-12T10:37:56.855545 - 
2024-12-12T10:38:03.830070 - got prompt
2024-12-12T10:38:03.890901 - D:\ComfyUI_windows_portable\ComfyUI\models\clip\siglip-so400m-patch14-3842024-12-12T10:38:03.890901 - 
2024-12-12T10:38:05.664600 - Loading VLM's custom vision model2024-12-12T10:38:05.664600 - 
2024-12-12T10:38:06.495637 - Requested to load SiglipVisionTransformer
2024-12-12T10:38:06.801788 - loaded completely 9.5367431640625e+25 809.1729736328125 True
2024-12-12T10:38:07.195348 - Requested to load ImageAdapter
2024-12-12T10:38:07.222257 - loaded completely 9.5367431640625e+25 41.0390625 True
2024-12-12T10:38:07.230481 - Loading tokenizer2024-12-12T10:38:07.230481 - 
2024-12-12T10:38:07.466292 - Loading LLM: unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit2024-12-12T10:38:07.466292 - 
2024-12-12T10:38:07.467292 - D:\ComfyUI_windows_portable\ComfyUI\models\LLM\Meta-Llama-3.1-8B-Instruct-bnb-4bit2024-12-12T10:38:07.467292 - 
2024-12-12T10:38:07.467292 - Successfully modified 'base_model_name_or_path' value in 'D:\ComfyUI_windows_portable\ComfyUI\models\Joy_caption_two\text_model\adapter_config.json'.2024-12-12T10:38:07.467292 - 
2024-12-12T10:38:07.474293 - Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
2024-12-12T10:38:11.497304 - !!! Exception during processing !!! cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\errors.py)
2024-12-12T10:38:11.510304 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 4310, in from_pretrained
    model.load_adapter(
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\integrations\peft.py", line 161, in load_adapter
    from peft import PeftConfig, inject_adapter_in_model, load_peft_weights
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\auto.py", line 31, in <module>
    from .config import PeftConfig
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils\__init__.py", line 22, in <module>
    from .loftq_utils import replace_lora_weights_loftq
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\peft\utils\loftq_utils.py", line 26, in <module>
    from huggingface_hub.errors import HFValidationError, LocalEntryNotFoundError
ImportError: cannot import name 'LocalEntryNotFoundError' from 'huggingface_hub.errors' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\errors.py)

2024-12-12T10:38:11.512305 - Prompt executed in 7.68 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":17,"nodes":[{"id":12,"type":"ShowText|pysssss","pos":[-544.5592041015625,6116.13330078125],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":12,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6,"label":"字符串"}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":8,"type":"LoadImage","pos":[-964.9876708984375,6068.6142578125],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[14],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["prompthero-prompt-82b4410e01a.webp","image"]},{"id":13,"type":"Joy_caption_two","pos":[-549.437744140625,5924.4697265625],"size":[315,126],"flags":{},"order":2,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":16,"label":"JoyCaptionTwo"},{"name":"image","type":"IMAGE","link":14,"label":"图像"}],"outputs":[{"name":"STRING","type":"STRING","links":[12],"label":"提示词"}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","long",false]},{"id":15,"type":"Joy_caption_two_load","pos":[-964.6824340820312,5924.1259765625],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[16],"slot_index":0,"label":"JoyCaptionTwo"}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]}],"links":[[12,13,0,12,0,"STRING"],[14,8,0,13,1,"IMAGE"],[16,15,0,13,0,"JoyTwoPipeline"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.083470594338842,"offset":[994.2169745523106,-5626.013558087792]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by 1695963547** [comment]
我也是这个错误

**Comment by AhamomentAI** [comment]
升级huggingface_hub到最新版本应该可以解决导入问题：
`pip install -U huggingface_hub`
