### ISSUE TITLE
Missing Base_Model_Path?

### ISSUE THREAD

**Issue by enoblegas** [EvilBT/ComfyUI_SLK_joy_caption_two#9]
I'm a hobbyist, sorry for the noobish qualities of myself, I am 100% sure I've done everything right, all models are in the folders they should be, I know this because I've gotten alpha one and the beta to work on other comfy joy captions nodes using the same clip and llm model. Dependencies have been downloaded. I'm not sure what else to say other than I just cannot get this to work.

# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two_load
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 258, in generate
    self.loadModels()

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 253, in loadModels
    self.pipeline.loadModels()

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 222, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 49, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11523055616
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-14 02:02:45,616 - root - INFO - Total VRAM 12288 MB, total RAM 16244 MB
2024-10-14 02:02:45,616 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-14 02:02:45,617 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-14 02:02:45,617 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-10-14 02:02:46,534 - root - INFO - Using pytorch cross attention
2024-10-14 02:02:47,744 - root - INFO - [Prompt Server] web root: C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path checkpoints C:\Forge\stable-diffusion-webui-forge\models\Stable-diffusion
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path configs C:\Forge\models/Stable-diffusion
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path vae C:\Forge\stable-diffusion-webui-forge\models\VAE
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path loras C:\Forge\stable-diffusion-webui-forge\models\Lora
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path upscale_models C:\Forge\models/ESRGAN
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path upscale_models C:\Forge\models/RealESRGAN
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path upscale_models C:\Forge\models/SwinIR
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path embeddings C:\Forge\embeddings
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path hypernetworks C:\Forge\models/hypernetworks
2024-10-14 02:02:47,746 - root - INFO - Adding extra search path controlnet C:\Forge\models/ControlNet
2024-10-14 02:02:48,581 - root - INFO - 
Import times for custom nodes:
2024-10-14 02:02:48,581 - root - INFO -    0.0 seconds: C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\Pysssss
2024-10-14 02:02:48,581 - root - INFO -    0.0 seconds: C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-10-14 02:02:48,581 - root - INFO -    0.2 seconds: C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-14 02:02:48,581 - root - INFO - 
2024-10-14 02:02:48,587 - root - INFO - Starting server

2024-10-14 02:02:48,587 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-14 02:03:23,238 - root - INFO - got prompt
2024-10-14 02:03:27,281 - root - ERROR - !!! Exception during processing !!! 
2024-10-14 02:03:27,292 - root - ERROR - Traceback (most recent call last):
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 258, in generate
    self.loadModels()
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 253, in loadModels
    self.pipeline.loadModels()
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 222, in loadModels
    self.clip_model = JoyClipVisionModel(self.load_device, self.offload_device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 49, in __init__
    assert (BASE_MODEL_PATH / "clip_model.pt").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-14 02:03:27,298 - root - INFO - Prompt executed in 4.05 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":4,"last_link_id":3,"nodes":[{"id":2,"type":"Joy_caption_two_load","pos":{"0":386,"1":132},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"JoyTwoPipeline","type":"JoyTwoPipeline","links":[1],"shape":3}],"properties":{"Node name for S&R":"Joy_caption_two_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"]},{"id":3,"type":"LoadImage","pos":{"0":214,"1":306},"size":[315,314],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["01.jpg","image"]},{"id":1,"type":"Joy_caption_two","pos":{"0":785,"1":214},"size":{"0":315,"1":126},"flags":{},"order":2,"mode":0,"inputs":[{"name":"joy_two_pipeline","type":"JoyTwoPipeline","link":1},{"name":"image","type":"IMAGE","link":2}],"outputs":[{"name":"STRING","type":"STRING","links":[3],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"Joy_caption_two"},"widgets_values":["Descriptive","long",false]},{"id":4,"type":"ShowText|pysssss","pos":{"0":1245,"1":232},"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[{"name":"text","type":"STRING","link":3,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]}],"links":[[1,2,0,1,0,"JoyTwoPipeline"],[2,3,0,1,1,"IMAGE"],[3,1,0,4,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[0,0]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by EvilBT** [comment]
1. Check whether the model path is correct and whether it has been completely downloaded.
2. Update the dependency to the latest version:
```
pip install -U .\custom_nodes\ComfyUI_SLK_joy_caption_two\requirements.txt
```
