### ISSUE TITLE
无法使用4bit模型 Cannot use 4bit Llama model

### ISSUE THREAD

**Issue by FYNIXqwq** [EvilBT/ComfyUI_SLK_joy_caption_two#94]
![image](https://github.com/user-attachments/assets/6fbaad5a-7644-4d61-848d-1c1839adfa4a)
在选择了如上的4bit模型后出现报错
![image](https://github.com/user-attachments/assets/b2b2abdf-e03a-4273-992a-546d7f66e062)

错误报告如下：

`.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

# ComfyUI Error Report
## Error Details
- **Node Type:** Joy_caption_two
- **Exception Type:** ValueError
- **Exception Message:** `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
## Stack Trace
```
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()

  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,

  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(

  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4034, in from_pretrained
    dispatch_model(model, **device_map_kwargs)

  File "/root/ComfyUI/venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 498, in dispatch_model
    model.to(device)

  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
    raise ValueError(

```
## System Information
- **ComfyUI Version:** v0.2.2-76-gbdd4a22
- **Arguments:** /root/ComfyUI/main.py --listen=0.0.0.0
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 16864378880
  - **VRAM Free:** 15557714104
  - **Torch VRAM Total:** 973078528
  - **Torch VRAM Free:** 40034488

## Logs
```
2024-12-15 15:22:47,375 - root - INFO - Total VRAM 16083 MB, total RAM 322079 MB
2024-12-15 15:22:47,375 - root - INFO - pytorch version: 2.3.1+cu121
2024-12-15 15:22:48,480 - root - INFO - xformers version: 0.0.27
2024-12-15 15:22:48,481 - root - INFO - Set vram state to: NORMAL_VRAM
2024-12-15 15:22:48,481 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-12-15 15:22:48,658 - root - INFO - Using xformers cross attention
2024-12-15 15:22:49,300 - root - INFO - [Prompt Server] web root: /root/ComfyUI/web
2024-12-15 15:22:55,012 - root - INFO - 
Import times for custom nodes:
2024-12-15 15:22:55,012 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/websocket_image_save.py
2024-12-15 15:22:55,012 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/sdxl_prompt_styler
2024-12-15 15:22:55,012 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
2024-12-15 15:22:55,013 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-12-15 15:22:55,013 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two
2024-12-15 15:22:55,013 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Manager
2024-12-15 15:22:55,013 - root - INFO -    0.0 seconds: /root/ComfyUI/custom_nodes/rgthree-comfy
2024-12-15 15:22:55,013 - root - INFO -    0.1 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
2024-12-15 15:22:55,013 - root - INFO -    0.9 seconds: /root/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-12-15 15:22:55,013 - root - INFO -    4.1 seconds: /root/ComfyUI/custom_nodes/Comfyui-ergouzi-Nodes
2024-12-15 15:22:55,013 - root - INFO - 
2024-12-15 15:22:55,029 - root - INFO - Starting server

2024-12-15 15:22:55,029 - root - INFO - To see the GUI go to: http://0.0.0.0:8188
2024-12-15 15:23:33,682 - root - WARNING - WARNING path /root/ComfyUI/models/checkpoints/v1-5-pruned-emaonly.safetensors exists but doesn't link anywhere, skipping.
2024-12-15 15:23:33,682 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'CheckpointLoader|pysssss' node.
2024-12-15 15:23:33,684 - root - ERROR - Traceback (most recent call last):
  File "/root/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/root/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/py/better_combos.py", line 167, in INPUT_TYPES
    populate_items(names, "checkpoints")
  File "/root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/py/better_combos.py", line 129, in populate_items
    names.sort(key=lambda i: i["content"].lower())
  File "/root/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/py/better_combos.py", line 129, in <lambda>
    names.sort(key=lambda i: i["content"].lower())
TypeError: string indices must be integers

2024-12-15 15:25:27,219 - root - INFO - got prompt
2024-12-15 15:25:44,532 - root - INFO - Requested to load SiglipVisionTransformer
2024-12-15 15:25:44,532 - root - INFO - Loading 1 new model
2024-12-15 15:25:44,874 - root - INFO - loaded completely 0.0 809.1729736328125 True
2024-12-15 15:25:45,458 - root - INFO - Requested to load ImageAdapter
2024-12-15 15:25:45,458 - root - INFO - Loading 1 new model
2024-12-15 15:25:45,473 - root - INFO - loaded completely 0.0 41.0390625 True
2024-12-15 15:26:01,813 - root - ERROR - !!! Exception during processing !!! `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
2024-12-15 15:26:01,814 - root - ERROR - Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4034, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 498, in dispatch_model
    model.to(device)
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

2024-12-15 15:26:01,815 - root - INFO - Prompt executed in 34.59 seconds
2024-12-15 15:43:27,353 - root - INFO - got prompt
2024-12-15 15:43:33,034 - root - ERROR - !!! Exception during processing !!! `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
2024-12-15 15:43:33,035 - root - ERROR - Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 383, in generate
    text_model = joy_two_pipeline.llm.load_llm_model()
  File "/root/ComfyUI/custom_nodes/ComfyUI_SLK_joy_caption_two/joy_caption_two_node.py", line 177, in load_llm_model
    text_model = AutoModelForCausalLM.from_pretrained(text_model_path,
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4034, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 498, in dispatch_model
    model.to(device)
  File "/root/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

2024-12-15 15:43:33,035 - root - INFO - Prompt executed in 5.67 seconds

**Comment by yw-2020** [comment]
今天也遇上了这个问题

**Comment by nanonanocat** [comment]
> 升级一下comfyui好了

我在manager中更新了comfyui，但还是报这个错，还需要更新其他的东西吗？

**Comment by jinnaluo0** [comment]
> I have solved this problem~ python -m pip install accelerate==1.2.0 python -m pip install transformers==4.47.0

能够成功反推了吗？
能用python -m pip list，把其它python模块的版本也发一下吗？

**Comment by nanonanocat** [comment]
> > I have solved this problem~ python -m pip install accelerate==1.2.0 python -m pip install transformers==4.47.0
> 
> 能够成功反推了吗？ 能用python -m pip list，把其它python模块的版本也发一下吗？

Package                           Version
--------------------------------- ------------------
absl-py                           2.1.0
accelerate                        1.2.0
addict                            2.4.0
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioice                            0.9.0
aioresponses                      0.7.6
aiortc                            1.9.0
aiosignal                         1.3.1
albucore                          0.0.16
albumentations                    1.4.15
altair                            5.5.0
annotated-types                   0.7.0
anthropic                         0.34.2
antlr4-python3-runtime            4.9.3
anyio                             4.4.0
APScheduler                       3.10.1
argcomplete                       3.5.1
argostranslate                    1.9.6
arrow                             1.3.0
attrs                             24.2.0
av                                12.3.0
awscli                            1.33.44
backoff                           2.2.1
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
bitsandbytes                      0.44.1
black                             24.10.0
blend_modes                       2.2.0
blind-watermark                   0.4.4
boto3                             1.34.123
botocore                          1.34.162
cachetools                        5.5.0
came-pytorch                      0.1.3
certifi                           2024.8.30
cffi                              1.17.1
chardet                           5.2.0
charset-normalizer                3.3.2
click                             8.1.7
clip-interrogator                 0.6.0
cmake                             3.30.3
color-matcher                     0.5.0
colorama                          0.4.4
coloredlogs                       15.0.1
colorlog                          6.8.2
colour-science                    0.4.6
contourpy                         1.3.0
cookiecutter                      2.6.0
cryptography                      43.0.1
cssselect2                        0.7.0
cstr                              0.1.0
ctranslate2                       4.5.0
cycler                            0.12.1
Cython                            3.0.0
dataclasses-json                  0.6.7
datamodel-code-generator          0.26.3
ddt                               1.7.2
decord                            0.6.0
deep-translator                   1.11.4
defusedxml                        0.7.1
Deprecated                        1.2.14
diffusers                         0.30.2
dill                              0.3.8
distro                            1.9.0
dnspython                         2.7.0
docker                            6.1.3
docker-pycreds                    0.4.0
docutils                          0.16
easydict                          1.13
einops                            0.8.0
einshape                          1.0
email_validator                   2.2.0
eval_type_backport                0.2.0
fairscale                         0.4.13
fastapi                           0.110.3
ffmpy                             0.3.0
filelock                          3.15.4
flatbuffers                       24.3.25
flet                              0.24.1
flet-core                         0.24.1
flet-runtime                      0.24.1
fonttools                         4.53.1
frozenlist                        1.4.1
fsspec                            2024.9.0
ftfy                              6.2.3
fvcore                            0.1.5.post20221221
gdown                             5.2.0
genson                            1.3.0
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.43
google-ai-generativelanguage      0.6.10
google-api-core                   2.22.0
google-api-python-client          2.151.0
google-auth                       2.36.0
google-auth-httplib2              0.2.0
google-cloud-core                 2.4.1
google-cloud-storage              2.18.2
google-crc32c                     1.6.0
google-generativeai               0.8.3
google-resumable-media            2.7.2
googleapis-common-protos          1.65.0
googletrans-py                    4.0.0
GPUtil                            1.4.0
grpcio                            1.67.1
grpcio-status                     1.67.1
h11                               0.14.0
h2                                4.1.0
hpack                             4.0.0
httpcore                          1.0.5
httplib2                          0.22.0
httptools                         0.6.4
httpx                             0.27.2
huggingface-hub                   0.27.0
humanfriendly                     10.0
hydra-core                        1.3.2
hyperframe                        6.0.1
idna                              3.8
ifaddr                            0.2.0
imageio                           2.35.1
imageio-ffmpeg                    0.5.1
imagesize                         1.4.1
img2texture                       1.0.6
importlib_metadata                8.5.0
inference-cli                     0.9.13
inference-gpu                     0.9.13
inference-sdk                     0.17.0
inflect                           5.6.2
iniconfig                         2.0.0
iopath                            0.1.10
isort                             5.13.2
jax                               0.4.31
jaxlib                            0.4.31
Jinja2                            3.1.4
jiter                             0.7.0
jmespath                          1.0.1
joblib                            1.4.2
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.7
kornia                            0.7.3
kornia_rs                         0.1.5
lark-parser                       0.12.0
lazy_loader                       0.4
lion-pytorch                      0.2.3
llvmlite                          0.43.0
loguru                            0.7.2
lxml                              5.3.0
manifold3d                        2.5.1
mapbox_earcut                     1.0.2
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
marshmallow                       3.23.1
matplotlib                        3.8.0
matrix-client                     0.4.0
mdurl                             0.1.2
mediapipe                         0.10.14
ml-dtypes                         0.4.0
mpmath                            1.3.0
mss                               9.0.2
multidict                         6.0.5
mypy-extensions                   1.0.0
narwhals                          1.18.4
networkx                          3.3
numba                             0.60.0
numpy                             1.25.2
oauthlib                          3.2.2
omegaconf                         2.3.0
onnxruntime                       1.19.2
onnxruntime-gpu                   1.15.1
open_clip_torch                   2.29.0
openai                            1.54.3
opencv-contrib-python             4.10.0.84
opencv-python                     4.10.0.84
opencv-python-headless            4.10.0.84
opt-einsum                        3.3.0
packaging                         24.1
pandas                            2.2.2
pathspec                          0.12.1
peft                              0.12.0
pendulum                          3.0.0
piexif                            1.1.3
pilgram                           1.2.1
pillow                            10.4.0
pip                               24.2
pixeloe                           0.0.10
platformdirs                      4.3.2
pluggy                            1.5.0
pooch                             1.8.2
portalocker                       2.10.1
prettytable                       3.12.0
prodigyopt                        1.1
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 6.0.0
proto-plus                        1.25.0
protobuf                          5.28.3
psutil                            6.0.0
PuLP                              2.9.0
py-cpuinfo                        9.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.1
pybase64                          1.4.0
pycollada                         0.8
pycparser                         2.22
pydantic                          2.9.1
pydantic_core                     2.23.3
pydantic-settings                 2.6.1
pydot                             3.0.2
pyee                              12.0.0
pygit2                            1.15.1
PyGithub                          2.4.0
Pygments                          2.18.0
PyJWT                             2.9.0
pylibsrtp                         0.10.0
PyMatting                         1.1.12
PyNaCl                            1.5.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.4
pypng                             0.20220715.0
pyreadline3                       3.4.3
PySocks                           1.7.1
pytest                            8.3.3
pytest-asyncio                    0.21.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-slugify                    8.0.4
pytz                              2024.2
PyWavelets                        1.7.0
pywin32                           306
PyYAML                            6.0.2
pyzbar                            0.1.9
qrcode                            7.4.2
redis                             5.2.0
referencing                       0.35.1
regex                             2024.7.24
rembg                             2.0.59
repath                            0.9.0
reportlab                         4.2.2
requests                          2.31.0
requests-file                     2.1.0
requests-toolbelt                 1.0.0
requirements-parser               0.11.0
rf-clip                           1.0
rich                              13.9.4
rich-argparse                     1.6.0
rpds-py                           0.20.0
rsa                               4.7.2
Rtree                             1.3.0
s3transfer                        0.10.3
sacremoses                        0.0.53
safetensors                       0.4.5
schedulefree                      1.4
scikit-image                      0.24.0
scikit-learn                      1.5.2
scipy                             1.14.1
seaborn                           0.13.2
segment-anything                  1.0
Send2Trash                        1.8.3
sentencepiece                     0.2.0
sentry-sdk                        2.18.0
setproctitle                      1.3.3
setuptools                        72.1.0
shapely                           2.0.1
shellingham                       1.5.4
six                               1.16.0
skypilot                          0.4.1
smmap                             5.0.1
sniffio                           1.3.1
sounddevice                       0.5.0
soundfile                         0.12.1
soupsieve                         2.6
spandrel                          0.3.4
stanza                            1.1.1
starlette                         0.37.2
structlog                         24.4.0
supervision                       0.22.0
surrealist                        1.0.5
svg.path                          6.3
svglib                            1.5.1
sympy                             1.13.2
tabulate                          0.9.0
termcolor                         2.4.0
text-unidecode                    1.3
threadpoolctl                     3.5.0
tifffile                          2024.8.30
time-machine                      2.16.0
timm                              0.6.13
tinycss2                          1.3.0
tldextract                        5.1.3
tokenizers                        0.21.0
toml                              0.10.2
tomli                             2.0.1
torch                             2.4.1+cu124
torchaudio                        2.4.1+cu124
torchscale                        0.3.0
torchsde                          0.2.6
torchvision                       0.19.1+cu124
tqdm                              4.66.5
trampoline                        0.1.2
transformers                      4.47.0
transparent-background            1.3.3
trimesh                           4.4.9
typer                             0.9.0
typer-config                      1.4.0
types-python-dateutil             2.9.0.20241003
types-setuptools                  75.5.0.20241122
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tzdata                            2024.1
tzlocal                           5.2
ultralytics                       8.2.92
ultralytics-thop                  2.0.6
uritemplate                       4.1.1
urllib3                           1.26.20
uvicorn                           0.32.0
vhacdx                            0.0.8.post1
voluptuous                        0.15.2
wandb                             0.18.6
watchdog                          4.0.2
watchfiles                        0.24.0
wcwidth                           0.2.13
webcolors                         24.11.1
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        13.1
wget                              3.2
wheel                             0.44.0
win32-setctime                    1.1.0
wrapt                             1.16.0
xatlas                            0.0.9
xxhash                            3.5.0
yacs                              0.1.8
yapf                              0.40.2
yarl                              1.9.11
zipp                              3.20.1
zxing-cpp                         2.2.0

**Comment by nanonanocat** [comment]
> > I have solved this problem~ python -m pip install accelerate==1.2.0 python -m pip install transformers==4.47.0
> 
> 能够成功反推了吗？ 能用python -m pip list，把其它python模块的版本也发一下吗？

我测试下来 就是accelerate和transformers版本的问题，注意更新comfyui的python而不是电脑上的python就行

**Comment by Sdreamtale** [comment]
The two dependent versions embedded in my comfyUI portable package for Python are python -m pip install accelerate 1.7.0
and python -m pip install transformers 4.51.3. When I downgraded to python -m pip install accelerate==1.2.0
and python -m pip install transformers==4.47.0, this error occurred:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matrix-client 0.4.0 requires urllib3~=1.21, but you have urllib3 2.4.0 which is incompatible.
mediapipe 0.10.21 requires numpy<2, but you have numpy 2.2.6 which is incompatible.
torchaudio 2.7.0+cu128 requires torch==2.7.0+cu128, but you have torch 2.7.0 which is incompatible.
torchvision 0.22.0+cu128 requires torch==2.7.0+cu128, but you have torch 2.7.0 which is incompatible.
