### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by jinnaluo0** [EvilBT/ComfyUI_SLK_joy_caption_two#95]
哪位能成功运行这个插件的，能pip list把模块列表的版本发一下吗，谢谢了！

我尝试过以下各种方法，均无法成功运行这个插件：
使用COMFYUI官方的整合包，使用秋叶1.3，秋叶1.4
尝试修改TORCH版本 2.1.2,2.3.1,2.5.1
尝试修改(升级或降级) transformers,accelerate版本
修改节点的temperature和top_p参数
按网上的指引修改代码：model.bfloat16()，tokenizer.pad_token = "[PAD]"   tokenizer.padding_side = "left"
......

**Comment by EvilBT** [comment]
报什么错了，贴一下

**Comment by jinnaluo0** [comment]
> 报什么错了，贴一下

None
[2024-12-17 13:11:43.112] ## ComfyUI-Manager: installing dependencies done.
[2024-12-17 13:11:43.112] ** ComfyUI startup time: 2024-12-17 13:11:43.112001
[2024-12-17 13:11:43.136] ** Platform: Windows
[2024-12-17 13:11:43.136] ** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
[2024-12-17 13:11:43.137] ** Python executable: D:\ComfyUI_windows_portable2\python_embeded\python.exe
[2024-12-17 13:11:43.137] ** ComfyUI Path: D:\ComfyUI_windows_portable2\ComfyUI
[2024-12-17 13:11:43.137] ** Log path: D:\ComfyUI_windows_portable2\ComfyUI\comfyui.log
[2024-12-17 13:11:43.181] [ComfyUI-Manager] Windows event loop policy mode enabled
[2024-12-17 13:11:43.182] 
Prestartup times for custom nodes:
[2024-12-17 13:11:43.182]    2.8 seconds: D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-12-17 13:11:43.182] 
Total VRAM 12287 MB, total RAM 32700 MB
[2024-12-17 13:11:47.014] pytorch version: 2.3.1+cu121
[2024-12-17 13:11:50.124] xformers version: 0.0.27
[2024-12-17 13:11:50.125] Set vram state to: NORMAL_VRAM
[2024-12-17 13:11:50.125] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-12-17 13:11:50.588] Using xformers cross attention
[2024-12-17 13:11:52.186] [Prompt Server] web root: D:\ComfyUI_windows_portable2\ComfyUI\web
[2024-12-17 13:11:52.188] Adding extra search path checkpoints D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/Stable-diffusion
[2024-12-17 13:11:52.189] Adding extra search path configs D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/Stable-diffusion
[2024-12-17 13:11:52.189] Adding extra search path vae D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/VAE
[2024-12-17 13:11:52.189] Adding extra search path loras D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/Lora
[2024-12-17 13:11:52.189] Adding extra search path loras D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/LyCORIS
[2024-12-17 13:11:52.189] Adding extra search path upscale_models D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/ESRGAN
[2024-12-17 13:11:52.189] Adding extra search path upscale_models D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/RealESRGAN
[2024-12-17 13:11:52.189] Adding extra search path upscale_models D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/SwinIR
[2024-12-17 13:11:52.189] Adding extra search path embeddings D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\embeddings
[2024-12-17 13:11:52.189] Adding extra search path hypernetworks D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/hypernetworks
[2024-12-17 13:11:52.189] Adding extra search path controlnet D:\sd-webui-aki-v4.6\sd-webui-aki-v4.6\models/ControlNet
[2024-12-17 13:11:53.273] ### Loading: ComfyUI-Manager (V2.51.9)
[2024-12-17 13:11:53.551] ### ComfyUI Revision: 2863 [4c82741b] | Released on '2024-11-26'
[2024-12-17 13:11:53.812] 
Import times for custom nodes:
[2024-12-17 13:11:53.812]    0.0 seconds: D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-12-17 13:11:53.812]    0.1 seconds: D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
[2024-12-17 13:11:53.812]    0.5 seconds: D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-12-17 13:11:53.812] 
[2024-12-17 13:11:53.820] Starting server

[2024-12-17 13:11:53.820] To see the GUI go to: http://127.0.0.1:8188
[2024-12-17 13:11:54.711] FETCH DATA from: D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-12-17 13:11:54.896] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-12-17 13:11:55.189] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-12-17 13:11:55.204] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-12-17 13:11:55.472] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-12-17 13:11:55.502] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-12-17 13:12:08.361] got prompt
[2024-12-17 13:12:08.394] D:\ComfyUI_windows_portable2\ComfyUI\models\clip\siglip-so400m-patch14-384
[2024-12-17 13:12:14.226] NumExpr defaulting to 6 threads.
[2024-12-17 13:12:21.293] Loading VLM's custom vision model
[2024-12-17 13:12:22.905] Prompt: Write a long descriptive caption for this image in a formal tone.
[2024-12-17 13:12:22.975] Requested to load SiglipVisionTransformer
[2024-12-17 13:12:22.975] Loading 1 new model
[2024-12-17 13:12:23.304] loaded completely 0.0 809.1729736328125 True
[2024-12-17 13:12:23.862] D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\transformers\models\siglip\modeling_siglip.py:574: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
[2024-12-17 13:12:24.017] Requested to load ImageAdapter
[2024-12-17 13:12:24.018] Loading 1 new model
[2024-12-17 13:12:24.123] loaded completely 0.0 41.0390625 True
[2024-12-17 13:12:24.145] Loading tokenizer
[2024-12-17 13:12:24.624] Loading LLM: unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit
[2024-12-17 13:12:24.624] D:\ComfyUI_windows_portable2\ComfyUI\models\LLM\Meta-Llama-3.1-8B-Instruct-bnb-4bit
[2024-12-17 13:12:24.626] Successfully modified 'base_model_name_or_path' value in 'D:\ComfyUI_windows_portable2\ComfyUI\models\Joy_caption_two\text_model\adapter_config.json'.
[2024-12-17 13:12:24.638] Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
[2024-12-17 13:12:39.814] !!! Exception during processing !!! probability tensor contains either `inf`, `nan` or element < 0
[2024-12-17 13:12:39.818] Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable2\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two\joy_caption_two_node.py", line 569, in generate
    generate_ids = text_model.generate(input_ids, inputs_embeds=input_embeds, attention_mask=attention_mask,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 2215, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable2\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 3249, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

[2024-12-17 13:12:39.820] Prompt executed in 31.46 seconds

----------------------------------------------------------------------------------------------------------------------------------

Package                           Version
--------------------------------- ------------------
absl-py                           2.0.0
accelerate                        1.0.1
addict                            2.4.0
aggdraw                           1.3.18.post0
aiofiles                          23.2.1
aiohttp                           3.9.5
aioresponses                      0.7.6
aiosignal                         1.3.1
albucore                          0.0.20
albumentations                    1.4.21
alibabacloud_credentials          0.3.2
alibabacloud_endpoint_util        0.0.3
alibabacloud_gateway_spi          0.0.1
alibabacloud-imageseg20191230     3.0.0
alibabacloud_openapi_util         0.2.2
alibabacloud-openplatform20191219 2.0.0
alibabacloud_oss_sdk              0.1.0
alibabacloud_oss_util             0.0.6
alibabacloud-tea                  0.3.5
alibabacloud_tea_console          0.0.1
alibabacloud_tea_fileform         0.0.5
alibabacloud_tea_openapi          0.3.8
alibabacloud_tea_util             0.3.11
alibabacloud_tea_xml              0.0.2
aliyun-python-sdk-core-v3         2.13.10
altair                            5.2.0
annotated-types                   0.6.0
antlr4-python3-runtime            4.9.3
anyio                             4.2.0
appdirs                           1.4.4
APScheduler                       3.10.1
argostranslate                    1.9.1
arrow                             1.3.0
asttokens                         2.4.1
astunparse                        1.6.3
attrs                             23.1.0
audioread                         3.0.1
av                                12.0.0
awscli                            1.33.44
backoff                           2.2.1
base58                            2.1.1
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
bitsandbytes                      0.45.0
black                             21.4b2
blend-modes                       2.1.0
blind-watermark                   0.4.4
blinker                           1.7.0
boto3                             1.34.123
botocore                          1.34.162
braceexpand                       0.1.7
cachetools                        5.3.2
certifi                           2023.11.17
cffi                              1.16.0
cfgv                              3.4.0
chardet                           5.2.0
charset-normalizer                3.3.2
click                             8.1.7
clip                              1.0
clip-interrogator                 0.6.0
clipseg                           0.0.1
cloudpickle                       3.0.0
cmake                             3.28.1
color-matcher                     0.5.0
colorama                          0.4.4
coloredlogs                       15.0.1
colorlog                          6.8.0
colour-science                    0.4.4
compel                            2.0.2
comtypes                          1.2.1
contourpy                         1.2.0
controlnet-aux                    0.0.7
cookiecutter                      2.6.0
cryptography                      41.0.7
cssselect2                        0.7.0
cstr                              0.1.0
ctranslate2                       4.5.0
cupy-cuda12x                      13.0.0
cycler                            0.12.1
Cython                            3.0.0
dashscope                         1.15.0
dataclasses-json                  0.6.7
datasets                          2.18.0
ddt                               1.7.1
decorator                         4.4.2
decord                            0.6.0
deep-translator                   1.11.4
deepdiff                          6.7.1
deforum                           0.1.8.dev1
defusedxml                        0.7.1
Deprecated                        1.2.14
diffusers                         0.31.0
dill                              0.3.8
diskcache                         5.6.3
distlib                           0.3.9
distro                            1.8.0
docker                            6.1.3
docker-pycreds                    0.4.0
docopt                            0.6.2
docstring_parser                  0.16
docutils                          0.16
easydict                          1.13
edge-tts                          6.1.10
einops                            0.7.0
embreex                           2.17.7.post4
eval_type_backport                0.2.0
executing                         2.0.1
face-alignment                    1.4.1
facenet-pytorch                   2.6.0
facexlib                          0.3.0
fairscale                         0.4.0
fal_client                        0.5.6
fastapi                           0.109.0
faster-whisper                    1.0.3
fastrlock                         0.8.2
ffmpeg-python                     0.2.0
ffmpy                             0.3.0
filelock                          3.13.1
filterpy                          1.4.5
fire                              0.5.0
Flask                             3.0.0
flatbuffers                       24.3.25
flet                              0.23.2
flet-core                         0.23.2
flet-runtime                      0.23.2
fonttools                         4.46.0
frozenlist                        1.4.0
fsspec                            2023.10.0
ftfy                              6.1.3
future                            1.0.0
fvcore                            0.1.5.post20221221
gast                              0.4.0
gdown                             5.2.0
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.40
glfw                              2.7.0
glitch_this                       1.0.3
google-ai-generativelanguage      0.6.2
google-api-core                   1.34.1
google-api-python-client          2.126.0
google-auth                       2.25.2
google-auth-httplib2              0.2.0
google-auth-oauthlib              1.0.0
google-cloud-core                 2.4.1
google-cloud-storage              2.14.0
google-crc32c                     1.6.0
google-generativeai               0.5.2
google-pasta                      0.2.0
google-resumable-media            2.7.2
googleapis-common-protos          1.63.0
googletrans-py                    4.0.0
GPUtil                            1.4.0
gradio                            4.8.0
gradio_client                     0.7.1
gradio_imageslider                0.0.17
grpcio                            1.62.1
grpcio-status                     1.48.2
h11                               0.14.0
h2                                4.1.0
h5py                              3.12.1
hpack                             4.0.0
httpcore                          1.0.2
httplib2                          0.22.0
httptools                         0.6.1
httpx                             0.27.2
httpx-sse                         0.4.0
huggingface-hub                   0.23.4
humanfriendly                     10.0
hydra-core                        1.3.2
hyperframe                        6.0.1
icecream                          2.1.3
identify                          2.6.1
idna                              3.4
image-reward                      1.5
imageio                           2.33.1
imageio-ffmpeg                    0.5.1
img2texture                       1.0.6
imgaug                            0.4.0
importlib-metadata                7.0.0
importlib-resources               6.1.1
inference-cli                     0.17.0
inference-gpu                     0.15.2
iniconfig                         2.0.0
insightface                       0.7.3
instructor                        1.6.3
intel-openmp                      2021.4.0
iopath                            0.1.9
ipython                           8.29.0
itsdangerous                      2.1.2
jax                               0.4.36
jaxlib                            0.4.36
jaxtyping                         0.2.31
jedi                              0.19.1
Jinja2                            3.1.4
jiter                             0.5.0
jmespath                          0.10.0
joblib                            1.3.2
json_repair                       0.30.1
jsonschema                        4.20.0
jsonschema-specifications         2023.11.2
kaldi-native-fbank                1.20.1
keras                             3.5.0
keyboard                          0.13.5
kiwisolver                        1.4.5
kornia                            0.7.4
kornia_rs                         0.1.3
lark                              1.1.9
lark-parser                       0.12.0
lazy_loader                       0.4
libclang                          16.0.6
librosa                           0.10.1
lightning-utilities               0.10.0
llama_cpp_python                  0.2.77
llvmlite                          0.41.1
lmdb                              1.5.1
loguru                            0.7.2
loralib                           0.1.2
lpips                             0.1.4
lxml                              4.9.4
mapbox-earcut                     1.0.1
Markdown                          3.5.1
markdown-it-py                    3.0.0
MarkupSafe                        2.1.3
marshmallow                       3.23.0
matplotlib                        3.8.2
matplotlib-inline                 0.1.7
matrix-client                     0.4.0
mdurl                             0.1.2
mediapipe                         0.10.9
mkl                               2021.4.0
ml-dtypes                         0.4.0
modelscope                        1.18.1
moviepy                           1.0.3
mpmath                            1.3.0
msgpack                           1.0.7
mss                               9.0.1
msvc_runtime                      14.40.33807
mttkinter                         0.6.1
multidict                         6.0.4
multiprocess                      0.70.16
mypy-extensions                   1.0.0
namex                             0.0.8
natsort                           8.4.0
nerfacc                           0.5.3
networkx                          3.2.1
ninja                             1.11.1.1
nodeenv                           1.9.1
numba                             0.58.1
numexpr                           2.8.8
numpy                             1.26.4
oauthlib                          3.2.2
ollama                            0.3.3
omegaconf                         2.3.0
onnx                              1.15.0
onnxruntime                       1.20.0
onnxruntime-gpu                   1.19.2
open_clip_torch                   2.26.1
openai                            1.52.2
openai-clip                       1.0.1
opencv-contrib-python             4.8.1.78
opencv-python                     4.8.0.76
opencv-python-headless            4.10.0.84
opensimplex                       0.4.5
opt-einsum                        3.3.0
optree                            0.12.1
ordered-set                       4.1.0
orjson                            3.9.12
packaging                         24.1
panda3d-gltf                      1.1.0
panda3d-simplepbr                 0.11.2
pandas                            2.2.3
parso                             0.8.4
pathspec                          0.12.1
peft                              0.13.2
pendulum                          3.0.0
piexif                            1.1.3
pilgram                           1.2.1
pillow                            11.0.0
pip                               24.3.1
pixeloe                           0.0.4
pixelsort                         1.0.1
platformdirs                      4.1.0
pluggy                            1.5.0
plyfile                           1.0.3
pooch                             1.8.0
portalocker                       2.8.2
pre_commit                        4.0.1
prettytable                       3.9.0
proglog                           0.1.10
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 6.0.0
prompt_toolkit                    3.0.48
proto-plus                        1.23.0
protobuf                          5.28.3
psd-tools                         1.9.34
psutil                            5.9.8
PuLP                              2.9.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           15.0.2
pyarrow-hotfix                    0.6
pyasn1                            0.5.1
pyasn1-modules                    0.3.0
pybase64                          1.4.0
pycocoevalcap                     1.2
pycocotools                       2.0.7
pycollada                         0.7.2
pycparser                         2.21
pydantic                          2.9.2
pydantic_core                     2.23.4
pydantic-settings                 2.3.4
pydot                             3.0.1
pydub                             0.25.1
pygame                            2.5.2
PyGetWindow                       0.0.9
pygit2                            1.15.0
PyGithub                          2.3.0
pyglet                            1.5.28
pygltflib                         1.0
Pygments                          2.17.2
pygrabber                         0.2
pyhocon                           0.3.61
PyJWT                             2.8.0
PyMatting                         1.1.12
PyMCubes                          0.1.6
pymeshlab                         2023.12.post1
PyNaCl                            1.5.0
pynvml                            11.5.0
PyOpenGL                          3.1.7
pyOpenSSL                         23.3.0
pyparsing                         3.1.1
pypng                             0.20220715.0
pyreadline3                       3.5.4
PyRect                            0.2.0
PySimpleGUI                       4.60.5
PySocks                           1.7.1
pytest                            8.3.3
pytest-asyncio                    0.21.1
python-dateutil                   2.8.2
python-dotenv                     1.0.1
python-multipart                  0.0.6
python-slugify                    8.0.4
pytorch-lightning                 2.2.1
pytorch-msssim                    1.0.0
pytz                              2023.3.post1
PyWavelets                        1.5.0
pywin32                           306
PyYAML                            6.0.1
pyzbar                            0.1.9
qrcode                            7.4.2
redis                             5.2.0
referencing                       0.32.0
regex                             2023.10.3
rembg                             2.0.53
repath                            0.9.0
reportlab                         4.0.8
requests                          2.31.0
requests-file                     2.1.0
requests-oauthlib                 1.3.1
requests-toolbelt                 1.0.0
requirements-parser               0.5.0
rf-clip                           1.0
rich                              13.9.4
rich-argparse                     1.4.0
roma                              1.4.3
rpds-py                           0.15.2
rsa                               4.7.2
Rtree                             1.1.0
ruff                              0.1.14
s3transfer                        0.10.2
sacremoses                        0.0.53
safetensors                       0.4.3
scenedetect                       0.6.4
scikit-image                      0.24.0
scikit-learn                      1.3.2
scipy                             1.14.1
seaborn                           0.13.0
segment-anything                  1.0
semantic-version                  2.10.0
Send2Trash                        1.8.3
sensevoice-onnx                   1.1.0
sentencepiece                     0.2.0
sentry-sdk                        2.13.0
setproctitle                      1.3.3
setuptools                        65.0.0
shapely                           2.0.2
shellingham                       1.5.4
shtab                             1.7.1
simple-lama-inpainting            0.1.1
simpleeval                        0.9.13
simsimd                           6.0.1
six                               1.16.0
skypilot                          0.5.0
smmap                             5.0.1
sniffio                           1.3.0
sounddevice                       0.4.6
soundfile                         0.12.1
soupsieve                         2.5
soxr                              0.3.7
spaces                            0.19.4
spandrel                          0.3.4
sse-starlette                     2.1.2
stack-data                        0.6.3
stanza                            1.1.1
starlette                         0.35.1
starlette-context                 0.3.6
stringzilla                       3.10.7
structlog                         24.4.0
supervision                       0.22.0
svg.path                          6.3
svglib                            1.5.1
swarm                             0.1.0
sympy                             1.13.1
tabulate                          0.9.0
tb-nightly                        2.18.0a20240725
tbb                               2021.12.0
tenacity                          9.0.0
tensorboard                       2.18.0
tensorboard-data-server           0.7.2
tensorflow                        2.18.0
tensorflow_intel                  2.18.0
tensorflow-io-gcs-filesystem      0.31.0
termcolor                         2.4.0
text-unidecode                    1.3
thop                              0.1.1-2209072238
threadpoolctl                     3.2.0
tifffile                          2023.12.9
time-machine                      2.16.0
timm                              0.6.13
tinycss2                          1.2.1
tldextract                        5.1.2
tokenizers                        0.20.3
tomesd                            0.1.3
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.3.1+cu121
torch_scatter                     2.1.2+pt23cu121
torchaudio                        2.3.1+cu121
torchmetrics                      1.2.1
torchscale                        0.3.0
torchsde                          0.2.6
torchtyping                       0.1.4
torchvision                       0.18.1+cu121
tqdm                              4.66.4
traitlets                         5.14.3
trampoline                        0.1.2
transformers                      4.46.3
transparent-background            1.3.1
trimesh                           4.0.5
triton                            3.1.0
typeguard                         2.13.3
typer                             0.9.0
typer-config                      1.4.0
types-python-dateutil             2.9.0.20240316
types-setuptools                  69.0.0.20240125
typing_extensions                 4.12.2
typing-inspect                    0.9.0
tyro                              0.8.5
tzdata                            2023.3
tzlocal                           5.2
ultralytics                       8.2.87
ultralytics-thop                  2.0.6
uritemplate                       4.1.1
urllib3                           1.26.18
uvicorn                           0.27.0
virtualenv                        20.27.1
wandb                             0.17.8
watchdog                          4.0.1
watchfiles                        0.22.0
Wave                              0.0.2
wcwidth                           0.2.12
webcolors                         24.8.0
webdataset                        0.2.86
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        11.0.3
Werkzeug                          3.0.1
wget                              3.2
wheel                             0.42.0
win32-setctime                    1.1.0
wldhx.yadisk-direct               0.0.6
wrapt                             1.14.1
xatlas                            0.0.9
xformers                          0.0.27
xxhash                            3.4.1
yacs                              0.1.8
yapf                              0.40.2
yarl                              1.9.3
zhipuai                           2.0.1
zipp                              3.17.0
zxing-cpp                         2.2.0

**Comment by jinnaluo0** [comment]
![111111](https://github.com/user-attachments/assets/a71194bc-7c4a-47f8-a179-050ea196ac21)
